### ISSUE TITLE
Thor Update error

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#102]
Thor Update always Stuck with below message.

In Command Window "Do Home()+'ThorFolder\Thor.app"

Requesting file CurrentItemNumber.txt from server.
Requesting file _thorVersionFile.txt from server.

Warm regards,
mk.
![thorerror2](https://github.com/VFPX/Thor/assets/31514812/5b43ed29-8504-4bff-8305-695ce8da1915)
![thorerror1](https://github.com/VFPX/Thor/assets/31514812/e56bf4f1-c9c4-4a9a-a98b-5cdb93eaec12)

**Comment by Jimrnelson** [comment]
@mksharmamk 

Looks like a problem trying to download the first file in the CFU process.

Does the following link work for you?

https://raw.githubusercontent.com/VFPX/Thor/master/ThorUpdater/_ThorVersionFile.txt

**Comment by mksharmamk** [comment]
No giving error as image attached.
Warm regards,
mk.
![thorerror3](https://github.com/VFPX/Thor/assets/31514812/d68bfd49-be14-4728-8d72-f44cf57bf057)

**Comment by Jimrnelson** [comment]
@mksharmamk 

So it looks like the problem is on your end.  For reasons that you will have to explore, you're being prevented from accessing the site from which Thor is downloaded.

**Comment by mksharmamk** [comment]
It was working Perfect last week.
Problem from 2/3 days only.

Warm regards,
mk.

**Comment by mksharmamk** [comment]
https://raw.githubusercontent.com/VFPX/Thor/master/ThorUpdater/_ThorVersionFile.txt

Above link not working on my pc.
what issue I check?

Warm regards,
mk.
![thorerror4](https://github.com/VFPX/Thor/assets/31514812/1cdbd219-6ed2-4c6b-8d5c-d88d516b15fc)

**Comment by Jimrnelson** [comment]
@mksharmamk 

Sorry, I really can't help on this one.  Maybe somebody else can offer some positive suggestions.

**Comment by mhoganid8** [comment]
It's working from my machines... Try these solutions: https://www.seoptimer.com/blog/website-taking-too-long-to-respond/

For the domain https://raw.githubusercontent.com/:

 - You can check DNS from the DOS command line and compare it against an online tool like https://mxtoolbox.com/DNSLookup.aspx
 - Make sure your local HOSTS file does not contain an entry for the address
 - Check your security software - disable it for testing and re-enable it after you get the results.
 - See if your ISP is blocking the https://raw.githubusercontent.com/ IP address or domain

HTH

Michael Hogan
Ideate, LLC
312-436-1097

Klaatu barada nikto

----- Original Message -----
From: mksharmamk ***@***.***)
Date: 05/22/23 07:57
To: VFPX/Thor ***@***.***)
Cc: Subscribed ***@***.***)
Subject: Re: [VFPX/Thor] Thor Update error (Issue #102)

No giving error as image attached.
Warm regards,
mk.

**Comment by mksharmamk** [comment]
Thank you,
How to check ISP is blocking the site ?

When i try to open the site:  https://raw.githubusercontent.com/  it open the site: https://github.com/

Warm regards,
mk.

**Comment by mksharmamk** [comment]
Now this link give the result as attached.

warm regards,
mk.
![thorerror5](https://github.com/VFPX/Thor/assets/31514812/86243973-181c-4c54-8990-addb24efb368)

**Comment by mhoganid8** [comment]
https://grok.lsu.edu/article.aspx?articleid=19328


Michael Hogan
Ideate, LLC
312-436-1097

Klaatu barada nikto

----- Original Message -----
From: mksharmamk ***@***.***)
Date: 05/23/23 09:38
To: VFPX/Thor ***@***.***)
Cc: Michael Hogan ***@***.***), Comment ***@***.***)
Subject: Re: [VFPX/Thor] Thor Update error (Issue #102)

Thank you,

But Thor - Check for Update not working
It Stuck with "Requesting file _ThorVersionFile.txt from server."

How to refresh your DNS cache ?

Warm regards,
mk.

**Comment by mksharmamk** [comment]
Thank you,
Done c:\ipconfig /flushdns
Successfully flushed the DNS Resolver Cache.

But when i run Do home()+"thorfolder\thor.app"
It stuck with message: "Requesting file CurrentItemNumber.txt from server."

Warm regards,
mk.

**Comment by mksharmamk** [comment]
@Jimrnelson
What is the link of CurrentItemNumber.txt  ?

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

https://raw.githubusercontent.com/VFPX/ThorNews/master/NewsItems/CurrentItemNumber.txt

**Comment by mksharmamk** [comment]
Thank you,
This file giving result as attached but stuck in VFP ?

Warm regards,
mk.
![Uploading thorerror6.jpg…]()

**Comment by mksharmamk** [comment]
What is the use of this file when we Do home()+"Thorfolder\thor.app" in command window ?

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

> What is the use of this file when we Do home()+"Thorfolder\thor.app" in command window ?

It's checking to see if there are new Thor News items since you last checked; or, if this is an initial installation, it will show you the most recent news item.

**Comment by mksharmamk** [comment]
Thank you,
This txt files open properly in chrome, but my vfp stuck if i do thor.app in command window.
What possible reasons should i check ?

Warm regards,
mk.
