### ISSUE TITLE
Error when I start up my development environment after checking boxes in Stratup tools

### ISSUE THREAD

**Issue by avianmanagement** [VFPX/Thor#105]
## 📝 Provide detailed reproduction steps (if any)

1. …Opened thor configuration and in the startup tools tools tab checked the boxes for IntellsenceX and BeautyfyX
2. …![image](https://github.com/VFPX/Thor/assets/5089118/7ac77b4a-81bd-4873-9197-276bb021a409)3. …

Restart VFP and get an error 

![image](https://github.com/VFPX/Thor/assets/5089118/51cfe8d8-90f7-4089-b090-075cdb510337)

![image](https://github.com/VFPX/Thor/assets/5089118/7b9737c4-056f-4887-8bb3-79ca1c0f9463)

The value of this.handle here is 0

I'm using the Promatrix framework in VFP

### ✔️ Expected result

Not to get an error

### ❌ Actual result

Error as above

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
@avianmanagement 

There are very few Thor tools for which "run at startup" makes sense.

You have chosen one of them (the only one I use):

![image](https://github.com/VFPX/Thor/assets/81179335/856584bb-d603-4ba4-b07c-075953379eca)

However, you don't want to turn it on for the other one you've chosen:

![image](https://github.com/VFPX/Thor/assets/81179335/034248bd-5270-4ead-a821-01dfd7e64e0f)

As the description says, BeautifyX operates on the current procedure (code window), which does not apply when you are starting Thor.

**Comment by Jimrnelson** [comment]
Well, yes, it is a good idea, and Thor provides for a way for tools to indicate that they should not appear on the "Run at Startup" page.

Unfortunately, the default value for the property that controls this ("CanRunStStartUp") is .T.  (In retrospect, a remarkably poor choice).

This means that the default for any tool is it CAN be run at startup, so removing tools from the list entails modifying each one to set the property to .T.  

And that simply is not going to happen.

**Comment by avianmanagement** [comment]
Thank you. 
I need to read the docs a little more as I thought this meant that this made it available to my current session in VFP rather than actually run the tool to do work.

**Comment by Jimrnelson** [comment]
Once you have run Thor.App at the beginning of your session, all tools are available to be run.

It's up to you to determine how to run them.  There are many different ways, actually, all under your control in the Thor Configuration form (Slt+F12)

1. From the "Thor Tools" menu
2. From the "Tool Launcher" form
3. From a hot key that you assign
4. From the system menu pad if you create your own menu pad item
5. From a popup menu that your create.
6. From the Thor toolbar.

The "run at startup" page applies to those few tools that you want to run immediately.
