### ISSUE TITLE
Location of LOCAL and #IF Preprocessor Directive

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#107]
## 📝 Provide a description of the new feature

There is an ongoing discussion in #104 how *CREATE LOCALS* feature should place LOCALS block, if 
- LOCALS should be placed on top
- the first line that is not
  - a comment
  - other compiler directive
  - empty
- no parameters block exists

#104 shows a situation, where within the #IF .. #ENDIF Preprocessor Directive a documentation snippet is placed, what for this case should be above LOCALs.

Others use similar preprocessor stuff for debug, so they need the LOCALS before. 

This issue is about discussing the problem.

**Comment by lscheffler** [comment]
I use PDM by Martina Jindrova for ages (2005 for all I knew), and it works with common VFP comments. Others do a block like
```
*************
*                 *
* ¯\_(ツ)_/¯ *
*                 *
*************
```

**I** use such directives on top of a method to (quick) switch the code for debug like having this block setting a bunch of #DEFINES, vars, wathever. Simulate parameters. It's just replacing .F. to .T. to turn stuff on. 

I think, on should assume nothing by a special case.

**Comment by avianmanagement** [comment]
I also use PDM which is really nice.
I like the west wind one with the header block I use as it produces a PDF manual automatically which is easily readable for all my prgs and classes.

In view of what you say, which makes perfect sense, I think your previous suggestion of a dummy lParameter statement below the code block would be my best option once it's implemented for locals to always add the local list after any parameter statement.

**Comment by lscheffler** [comment]
I think about a marker, like a special comment, to avoid the extra LPARA what is a waste of time, but this is odd to document (Create Locals documentation). But then, there are directives of BeautifyX nobody knows anyway. :)

**Comment by avianmanagement** [comment]
A start of code marker would be a very good idea I think.

If present the locals code sees that as the start of the code and could then insert just after that, or after a real parameter statement if that occurred after the marker.

As you say it would avoid the extra dummy LPAR which would be a little confusing in code anyway.

**Comment by Jimrnelson** [comment]
Am wondering if instead of a new special marker, one used  #IF 1=0  (instead of #IF .F.) as the marker for "this section is never code and the locals can follow it"

For that matter, #IF !.T.   an even curiouser statement

**Comment by avianmanagement** [comment]
That sounds good, but doing that the locals code still has to figure out the end of that block.  Not a big deal I guess just look for the next  #ENDIF I assume.

If one used a marker to mark the start of ones code then the locals code would only need to locate that and then the code starts after that and place the locals list that or after a LPAR statement that followed it if any.

That way people who what it to work as it does now, other then the need to be after a LPARA statement, just don't have the marker in their code so it just behaves as before

**Comment by lscheffler** [comment]
I think I will do it as follows.

BeautifyX knows **{PEME:*]** switches. It's hard to find and to know, but for example [here](https://github.com/VFPX/PEMEditor/blob/master/Documentation/pemeditor_tools_beautifyx.md).

I simply invent a **{PEME:LOCALSAFTER}** that might be placed anywhere, and does the same job as parameters statement.   
It simply means: place the declaration before the next line that is not comment, declaration and so on.

Since it works like parameters (resetting the position) the last line with *parameters* or *{PEME:LOCALSAFTER}* will win.
For your use case, simply do like
```
LPARAMETERS tcX1
 
#IF .f. &&{PEME:LOCALSAFTER}
....
```

----
It has some problems - logically LOCALs might be placed in the middle of anything, and if issued as last statement, the LOCALs will not be inserted at all (there is nothing to place LOCLAs before, by the way it's coded)   
But this is the users choice.
