### ISSUE TITLE
Version info incorrect

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#11]
Was snooping around Thor files. Found Thor\ThorVersion.txt file
It has one record: Thor 1.42.13 - June 18, 2016   Wait, WHAT?
I know Thor has run updates, it checks every time I start.
Is this an orphan?

**Comment by rschummer** [comment]
Hi Bob, 

The core of Thor is solid and does not need to change. It is all the tools developers create for themselves and other VFP developers that are really add-ons to the core of Thor.

**Comment by DougHennig** [comment]
Also, keep in mind that Jim Nelson is no longer maintaining Thor, so someone else making changes (such as me) may not remember to update ThorVersion.txt.
