### ISSUE TITLE
url working with chrome but not working with wininet.Dll 

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#110]
If i paste below link in Chrome then working proper but not working with wininet.Dll 
https://raw.githubusercontent.com/VFPX/Thor/master/ThorUpdater/_ThorVersionFile.txt

I am using Windows 11

What should i Check ?

I am testing with below code:-

Create Cursor xtemp (mtemp m)
Append BLANK IN xtemp 
***** below url working**
Replace mtemp With ReadURL("http://www.microsoft.com")
Append BLANK IN xtemp 
***** This url Not working**
Replace mtemp With ReadURL("https://raw.githubusercontent.com/VFPX/Thor/master/ThorUpdater/_ThorVersionFile.txt")
BROWSE

Procedure ReadURL
Lparameters pcUrlName
*!*	Set Step On
Declare Integer InternetOpen In wininet.Dll String sAgent, ;
    INTEGER lAccessType, String sProxyName, ;
    STRING sProxyBypass, Integer lFlags

Declare Integer InternetOpenUrl In wininet.Dll ;
    INTEGER hInternetSession, String sUrl, String sHeaders, ;
    INTEGER lHeadersLength, Integer lFlags, Integer lContext

Declare Integer InternetReadFile In wininet.Dll Integer hfile, ;
    STRING @sBuffer, Integer lNumberofBytesToRead, Integer @lBytesRead

Declare short InternetCloseHandle In wininet.Dll Integer hInst

#Define INTERNET_OPEN_TYPE_PRECONFIG 0
#Define INTERNET_OPEN_TYPE_DIRECT 1
#Define INTERNET_OPEN_TYPE_PROXY 3
#Define SYNCHRONOUS 0
#Define INTERNET_FLAG_RELOAD 2147483648
#Define CR Chr(13)

Local lsAgent, lhInternetSession, lhUrlFile, llOk, lnOk, lcRetVal, lcReadBuffer, lnBytesRead
lsAgent = "VPF 7.0"
lhInternetSession = InternetOpen( lsAgent, INTERNET_OPEN_TYPE_PRECONFIG, '', '', SYNCHRONOUS)

If lhInternetSession = 0
    Wait Window "Internet session cannot be established" Time 2
    Return .Null.
Endif

lhUrlFile = InternetOpenUrl(lhInternetSession, pcUrlName, '', 0, INTERNET_FLAG_RELOAD, 0)

If lhUrlFile = 0
    Wait Window "URL cannot be opened"
    Return .Null.
Endif

lcRetVal = ""
llOk = .T.
Do While llOk
    lsReadBuffer = Space(32767)
    lnBytesRead = 0
    lnOk = InternetReadFile( lhUrlFile, @lsReadBuffer, Len(lsReadBuffer), @lnBytesRead)
    If ( lnBytesRead > 0 )
        lcRetVal = lcRetVal + Left( lsReadBuffer, lnBytesRead )
    Endif
    llOk = ( lnOk = 1 ) And ( lnBytesRead > 0 )
Enddo
InternetCloseHandle( lhUrlFile )
InternetCloseHandle( lhInternetSession )
Return lcRetVal

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

Is this still an open issue?

**Comment by mksharmamk** [comment]
Issue Resolved.

Warm regards,
mk.
