### ISSUE TITLE
classdefinition TOOLS not found in IntellisenseX

### ISSUE THREAD

**Issue by tomkn** [VFPX/Thor#113]
Hello,

I installed Thor from scratch into c:\develop\fox9\thor as described on project page
Then I open a new program and type oapp. (oapp is our global app object defined on startup)
I get the error "classdefinition TOOLS not found", filename in Program() seems to be random.

Debugger shows lineno 33 , here  is part of the code 
Otherwise
		lcClass	   = Getwordnum (lcClassName, 1)
		lcClassLib = Getwordnum (lcClassName, Getwordcount (lcClassName))
		lcFileName = Execscript (_Screen.cThorDispatcher, 'Full Path=' + lcClassLib)
		Do Case
			Case lnPCount < 2
				loObject   = Newobject (lcClass, lcFileName)

In commandwindow it offers all propertys of oapp so it a valid object)

lcclass = "tools"
lcclasslib = "pemeditor"
lcfilename = ""

Thanks for help
Tom

**Comment by Jimrnelson** [comment]
My apologies, a mis-statement,  I meant to write:

These projects were developed independently but over time but have grown to be _inter-dependent_, so they may be necessary even if you don't think you're using them.

**Comment by tomkn** [comment]
Hello Jim,

 

THNAKS a lot for the fast answer.

I installed all of the tools you mentioned (pem editor, thor repositor, intellisensex and goto definition), but there is still the same error.

 



 

Best regards

Tom

 

 

Von: Jimrnelson ***@***.***> 
Gesendet: Donnerstag, 8. Juni 2023 15:28
An: VFPX/Thor ***@***.***>
Cc: tom knauf ***@***.***>; Author ***@***.***>
Betreff: Re: [VFPX/Thor] classdefinition TOOLS not found in IntellisenseX (Issue #113)

 

My apologies, a mis-statement, I meant to write:

These projects were developed independently but over time but have grown to be inter-dependent, so they may be necessary even if you don't think you're using them.

**Comment by Jimrnelson** [comment]
Tom --

Can you paste in screenshot(s) of the debugger windows?

I need more information to tell what is going on.

(I have to assume you have closed out of VFP and restarted)

**Comment by tomkn** [comment]
Hello Jim,

 

S O R R Y.

I think I found it (a bit of it :))

 

If I set oapp from the command prompt, it works.

oapp = createob("empty")

ADDPROPERTY(oapp,"test","1")

? oapp.test



 

 

If I try to use it after our direct.prg has created the environment incl. oapp, it fails.

So the problem is on my side, something interferes , maybe set classlib,… which iss et by our program.

 



 

 

Best regards and thanks again

Tom

 

Von: Jimrnelson ***@***.***> 
Gesendet: Donnerstag, 8. Juni 2023 15:56
An: VFPX/Thor ***@***.***>
Cc: tom knauf ***@***.***>; Author ***@***.***>
Betreff: Re: [VFPX/Thor] classdefinition TOOLS not found in IntellisenseX (Issue #113)

 

Tom --

Can you paste in screenshot(s) of the debugger windows?

I need more information to tell what is going on.

(I have to assume you have closed out of VFP and restarted)

**Comment by Jimrnelson** [comment]
That's kind of mystifying to me, still, as Thor does not use or reference ClassLib.

However, in any case, I am glad you are narrowing in on the issue.
