### ISSUE TITLE
FoxBin2Prg not found

### ISSUE THREAD

**Issue by MeindertVos** [VFPX/Thor#114]
I am not sure if this has to do with the recent update but it looks like I found an error in Thor. 

I took following steps: 
- download and install Thor
- using Thor check for updates, install foxbin2prg and bin2text
- I am trying to start bin2text as suggested by it's docs:
![image](https://github.com/VFPX/Thor/assets/39734014/103ef010-95b2-4969-8ddf-a2a1f1ce353b)

After a while the debugger opens and it appears that lcFoxBin2prg = .null. after these lines:
![image](https://github.com/VFPX/Thor/assets/39734014/78bb8cff-3324-44b0-be10-791c4f47ba9b)

I verified this by copying the execscript command to my command window: it returns .NULL. 

It is possible of course that I am overlooking something, please let me know if that is the case.

**Comment by Jimrnelson** [comment]
@MeindertVos @lscheffler 

If you have just installed Thor, there are some other downloads that you should install as well besides those that you indicated.

Run Check For Updates again and download all of these:  Thor Repository, PEM Editor, IntellisenseX, GoToDefinition.  

Then try your code again.  

/ Jim

**Comment by MeindertVos** [comment]
Thanks for the quick response! You are right, the Repository was missing. 

Thanks again, Meindert

**Comment by lscheffler** [comment]
@Jimrnelson, thanks for the link, there is an unexpected problem.

Would you mind to open op *Discussions* for this repo? On top bar *Settings* -> General -> Scroll down to *Features* ->check *Discussions*, There is a template generator.

I have ongoing questions, and some stuff that I do not understand and need to discuss (sorry, the best way to get stuff in my brain) and this wrong on the isssues.

**Comment by lscheffler** [comment]
@MeindertVos Hi, I'm the dev for Bin2Text. Would you please help me out where I point to that way to call Bin2Text?
All I see is
```
lcFile   = Execscript (_Screen.cThorDispatcher, "Tool Folder=")+'Components\Bin2Text\Bin2Text.app'
lcFolder = {Your local "root "folder to process from}
DO InitMenu IN (m.lcFile) WITH (m.lcFolder)
```
But this should run like
`DO InitMenu IN "[..]\Thor\Installed Files\Thor\Tools\Components\Bin2Text\Bin2Text.app" WITH {Your local folder}`

That says:
Run *InitMenu* in *Bin2Text.app*, set **{Your local folder}** as project folder for settings, finding git repo etc. Not any Thor folder. Next to foxuser.dbf is a good choice.   
In the way you call it, you say the *Thor\Installed Files\Thor\Tools\Components\Bin2Text\* is your project home - that will not work.
The settings are project-local, not per machine or user.

If the doc needs to be more clear on this, pleas let me know.

**Comment by Jimrnelson** [comment]
> @Jimrnelson, thanks for the link, there is an unexpected problem.
> 
> Would you mind to open op _Discussions_ for this repo? On top bar _Settings_ -> General -> Scroll down to _Features_ ->check _Discussions_, There is a template generator.
> 
> I have ongoing questions, and some stuff that I do not understand and need to discuss (sorry, the best way to get stuff in my brain) and this wrong on the isssues.

I don't understand why you are asking me to start a Discussion here -- can't you start it yourself?  I don't have anything that I need to discuss about this topic, which has been resolved.  I understood the response form @MeindertVos to indicate that it was taken care of by downloading the usual Thor projects.

**Comment by lscheffler** [comment]
I guess you do not understand discussions. Now Thor on githun is like that:   
![grafik](https://github.com/VFPX/Thor/assets/27769909/5eb4b420-0b5f-4ac1-8cc9-35715bc2df6c)   
What I mean is like that:   
![grafik](https://github.com/VFPX/Thor/assets/27769909/e34612f8-f3dc-4070-b801-3eca4f8dc9b1)

A topic where one can *discuss* stuff that is not an issue or feature request

**Comment by Jimrnelson** [comment]
@lscheffler @DougHennig 

For VFPX/Thor, I do not see either "Discussions" or "Settings", so I do not understand what you are asking of me.

Maybe Doug can access/create a Discussions button.

**Comment by lscheffler** [comment]
Ah, then Doug is managing. Beg your Pardon. Something **I** have no idea how to find on github. It was a 50/50    

@DougHennig would please set up Discussions for this project? See https://github.com/VFPX/Thor/issues/114#issuecomment-1586076437   
And I would please you to alter the README.md and fill in the project manager in. :D 

Thank you.

**Comment by MeindertVos** [comment]
> @MeindertVos Hi, I'm the dev for Bin2Text. Would you please help me out where I point to that way to call Bin2Text? All I see is
> 
> ```
> lcFile   = Execscript (_Screen.cThorDispatcher, "Tool Folder=")+'Components\Bin2Text\Bin2Text.app'
> lcFolder = {Your local "root "folder to process from}
> DO InitMenu IN (m.lcFile) WITH (m.lcFolder)
> ```
> 
> But this should run like `DO InitMenu IN "[..]\Thor\Installed Files\Thor\Tools\Components\Bin2Text\Bin2Text.app" WITH {Your local folder}`
> 
> That says: Run _InitMenu_ in _Bin2Text.app_, set **{Your local folder}** as project folder for settings, finding git repo etc. Not any Thor folder. Next to foxuser.dbf is a good choice. In the way you call it, you say the *Thor\Installed Files\Thor\Tools\Components\Bin2Text* is your project home - that will not work. The settings are project-local, not per machine or user.
> 
> If the doc needs to be more clear on this, please let me know.

Hi @lscheffler, I did not understand that with 'local root folder to process from', you meant the project folder so I figured that the best place for Bin2Text tables would be in it's own folder. I have changed that now, and see a new table in my project directory. 
Many thanks, Meindert

**Comment by lscheffler** [comment]
Any better idea to express this? My English is limited.

**Comment by DougHennig** [comment]
@lscheffler I turned on Discussions.

**Comment by Jimrnelson** [comment]
> Any better idea to express this? My English is limited.

@lscheffler 

I'm not sure what you are referring to here.  Can you highlight what text you would like help with?

I'm sure that it doesn't help that I am not familiar with your project.

**Comment by lscheffler** [comment]
For example [README.md](https://github.com/lscheffler/bin2text#via-thor) gives some advice how to Bin2Text - it looks like one can read this is in the original message of this issue, first picture.

**Comment by Jimrnelson** [comment]
> For example [README.md](https://github.com/lscheffler/bin2text#via-thor) gives some advice how to use Bin2Text - it looks like one can read this is in the original message of this issue, first picture.

@lscheffler 

I'm pretty sure that the problem is on my end, not yours, but can you please explain what the question is here?

**Comment by lscheffler** [comment]
¯\_(ツ)_/¯   
Look up the first picture of this issue. The OT expresses, this call is the result of the advice given  [here](https://github.com/lscheffler/bin2text#via-thor). I do not see how one could read it this way. And I like to do better.

**Comment by Jimrnelson** [comment]
@lscheffler 

Your documentation looks fine to me.

It's impossible to write documentation in such a way that everybody will understand it perfectly the right time.

**Comment by lscheffler** [comment]
ok, Thank you.
