### ISSUE TITLE
Do Loop after update

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#118]
## 📝 Provide detailed reproduction steps (if any)

1. I run CFU, it updated 
2. later I checked PEMEditor in CFU trying to reinstall it (force update)
3. Started BeautifyX via Thor Menu

### ✔️ Expected result

Run

### ❌ Actual result

Failed do to too many DO calls.

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
Odd one, something that I can reproduce but not consistently.

**Comment by lscheffler** [comment]
I opened a simple prg window and added something like   
`SELECT * from bla group by 1,2,mu into cursor xx` to work on https://github.com/VFPX/PEMEditor/issues/40, it fails all the time.

**Comment by Jimrnelson** [comment]
Fails how?  Did you restart VFP?

**Comment by Jimrnelson** [comment]
> I normally have multiple instances of VFP (with Thor) open.

A technical correction of terminology here.  Thor is never "open".  When you run it, it assigns hot keys, build menus, creates popup menus, creates a tool bar, creates some properties in _Screen -- and then is done.  It is not running, there is no object running things.

That is why it survives clear all

**Comment by lscheffler** [comment]
Sure. Open in the sense that the menus are instantiated, might run something in the very moment, in the middle of debugging, left stuff in VFP's odd caching system.   
IOW: The file system *might* be not clear while running CFU. That's  why I didn't report the problem the first place.
