### ISSUE TITLE
Install instructions revision

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#12]
In reviewing the Install instructions, I think the "Installing Thor" section (~line 20 of the .md file) would be clearer if it were changed to:

After you have downloaded the Zip file, do the following:
  Extract Thor.app from the zip [Thor-master\Thor folder] into the installation folder.
  From the VFP Command window:
    CD <to the install folder>
    Clear all
    Do Thor.app

<Extract <the other stuff> to <wherever it should go>>

I've had 2 colleagues in the recent past screw up the install and wind up with something other than expected...
Not sure what or how they did to accomplish that, but I think they missed the "Extract...to the install folder..." Step.
The above seems more fool-proof to me, especially for option 2, which is our standard for putting Thor under the VFP Home directory.

**Comment by BobWilkes** [comment]
OOPS. The CD command should be: CD <install folder>

**Comment by BobWilkes** [comment]
OK. The editor doesn't like 'less than' or 'greater than' brackets.
How about: CD {the install folder}

**Comment by nstenz-kds** [comment]
This is still an issue. `Docs/Thor_install.md` states:

> Extract the Thor-master\Thor subdirectory from the ZIP file to the installation folder of your choice (see details below on how to choose an installation folder. After this step your installation folder should only contain the Source folder and Thor.APP.

After cloning Thor-master, there is no `Thor` directory. There is a `ThorUpdater` directory, which contains `Thor.zip`. The instructions should state that you need to extract `ThorUpdater\Thor.zip`. Is "the ZIP file" `Thor.zip`? There's no mention that it's located in the `ThorUpdater` directory or that it is named `Thor.zip`.

**Comment by DougHennig** [comment]
The documentation has been fixed: you need to extract the Thor-master\Installed Files subdirectory.
