### ISSUE TITLE
Thor PEM Update fails

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#122]
## 📝 Provide detailed reproduction steps (if any)

1. Using Thor 1.45.25
2. No projects open
3. PEM editor running
4. Run Thor Check for Updates. Get PEM Update avail. Select Update
5. File is downloaded but somewhere during install, issues an error:
![image](https://github.com/VFPX/Thor/assets/34778960/47e87a4a-57c5-4ec9-a687-5cd85ae243ab)
I still get error if I close PEM Ed and Release _OPemEditor variable
Not sure what I've done, as it used to work... but it seems that I've generated Thor angst!
and an 'angstfull' Thor is not good.
### ✔️ Expected result

Installation of update (Duh!)

### ❌ Actual result

Thor update fails

**Comment by Jimrnelson** [comment]
Bob --

If this problem is entirely because of what's happening within VFP, I suggest the following:

1. Close all VFP sessions
2. Open a new session, but do not start or run PEMEditor or any other Thor tool.
3. Try Check For Updates again

If this doesn't work then I would check for other processes that may be accessing the folder -- Explorer, for instance, would be a prime suspect.

If all else fails, reboot and try steps 1-3 above.

**Comment by BobWilkes** [comment]
UNACCEPTABLE.
I have Thor configured to run PEMEd on startup, as it should be.
That makes your step 2 impractical and then step 3 impossible.

What I wound up doing is:
1. Run VFP. Change Thor config to NOT run PEMEd at start.
2. Restart VFP.
3. Ask Thor to check for updates.
     Which it did and happily installed PEMEd update
4. Reconfigure Thor to run PEMEd at starat.
5. Restaert VFP.

WAY TOO involved to be practical on a day-to-day basis.
As PEMEd and Thor are closely intertwineded, I would hope that this 
issue can be resolved...
Thor should be able to perform the update.

AFAIK, no other process has a hold on the PEM Editor folder.
Since the above worked, I can only assume that it's the PEM Editor 
itself that has a file in that folder open and that the update install 
process doesn't correctly shut down PEMEd before it tries to copy files.

------ Original Message ------
...

**Comment by DougHennig** [comment]
"UNACCEPTABLE" seems a little harsh for a free, volunteer-created tool as useful as Thor is.

We're glad you got it to work and hope to have a workaround before the next update to PEMEditor. No promises, as we can't imagine what we could do differently.

**Comment by BobWilkes** [comment]
Yes, that was a bit harsh. Perhaps too much "frustration influence", so 
an appology is in order.
Didn't mean to raise hackles, Doug...
You and many other s have done a super job of providing enhancements for 
VFP and will NEVER get enough crfedit for all that youj've done for the 
community.
KUDOS to all!

Perhaps these tools are so good that we've come to expect them to be 
perfect in every way and are dissapointed when they fall short.
It;s not a perfect world, though...and, as programmers, we're caught 
between the dog and the fire hydrant.
I consider myself a "rational perfectionist"...striving for perfection, 
knowing **** well I'll never get there.
So just delete that comment and insert
"Not the best solution for the issue"

If I can provide any info that will help troubleshoot the cause, please 
let me know.
After all, it may well be something in my environment that's causing it, 
especially if you can't recreate the problem.


------ Original Message ------
From "Doug Hennig" ***@***.***>
To "VFPX/Thor" ***@***.***>
Cc "BobWilkes" ***@***.***>; "Author" 
***@***.***>
Date 6/14/2023 10:32:41 AM
Subject Re: [VFPX/Thor] Thor PEM Update fails (Issue #122)

**Comment by Jimrnelson** [comment]
Very nice and this turned out much better.  Sent from my iPhoneOn Jun 14, 2023, at 10:32 AM, Doug Hennig ***@***.***> wrote:﻿
"UNACCEPTABLE" seems a little harsh for a free, volunteer-created tool as useful as Thor is.
We're glad you got it to work and hope to have a workaround before the next update to PEMEditor. No promises, as we can't imagine what we could do differently.

**Comment by Jimrnelson** [comment]
@BobWilkes 

You can avoid this issue by having Thor update automatically on a schedule,, as many do -- say, weekly.

`RunThor(7)` && starts up and runs Check For Updates once a week.

Run this way, "Check For Updates" is run before any Thor startup tools.

**Comment by BobWilkes** [comment]
That's how it normally runs.
But I was having an issue mid-week with another app and they both popped up
with update available.

Guess I'll avoid it for any future manual updates.
