### ISSUE TITLE
Thor update error

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#126]
## 📝 Provide detailed reproduction steps (if any)

1. open VFP with Thor update on startup
2. some stuff like projects is loaded
3. no other VFP instance running
4. Thor likes to update itself
5. this is VFPA

### ✔️ Expected result

update Thor

### ❌ Actual result

Error 1184 in line 629 of createrunthorprg

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by Jimrnelson** [comment]
@lscheffler 

That's a new one.  What happens if you ignore the error?  It looks to me like it might not be consequential.

**Comment by lscheffler** [comment]
I can not IGNORE. My startup - errorhandler catches in. I can not look into the code there, the code looks like Execscript and is not available.

First I killed VFP, the error reappear.   
Same with VFP9 SP2   
Then I simply issued RETURN from the handler, and it runs through. And runs since.

Thor options form shows 1.45.26 - June 21, 2023
