### ISSUE TITLE
Check for Updates URL cannot be opened

### ISSUE THREAD

**Issue by rawilliamsjr** [VFPX/Thor#13]
From the Thor menu
Check for Updates
Requesting file Updates.zip?= <temp filename> from server.
URL cannot be opened

**Comment by rschummer** [comment]
It appears there is something wonky with the domain where the thorupdates are hosted. I'll have to check into that on the weekend. Yippee! We just renewed the domain hosting for a year too.

**Comment by rschummer** [comment]
This has been resolved. Thor's Check for Updates is working again.

**Comment by rawilliamsjr** [comment]
Thanks for the quick response and resolution.
