### ISSUE TITLE
Problem occurs during Thor version check of GitUtilities

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/Thor#130]
## 📝 Provide detailed reproduction steps (if any)

1. … Have Thor check for updates
2. … When it gets to checking the version file for the GitUtilities it creates an error
3. … You can continue with the check and all works fine except the GitUtilities will have to be manually updated

### ✔️ Expected result

I expect Thor to be able to check for all the included repositories and not get an error on this one.

### ❌ Actual result

An error occurs stating that a VersionInfo.txt cannot be found.

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
![GIT Issue](https://github.com/VFPX/Thor/assets/34104227/4ec5995b-89fa-4b08-949a-4ea781a9d0d6)

**Comment by Jimrnelson** [comment]
@CHamlinPNP @DougHennig 

Have you tried this again?  I just tried it and did not have any problems updating Git Utilities from Thor's Check For Updates.

**Comment by DougHennig** [comment]
Same here: no issue. Must have been a temporary glitch.

**Comment by CHamlinPNP** [comment]
Just tried it again and I continue to get the error. This has not been corrected from what I see. Something is failing.
![2023-08-08_10-15-24](https://github.com/VFPX/Thor/assets/34104227/f98a0ebf-cb75-4be7-b8f3-25e3ff527dda)

**Comment by DougHennig** [comment]
I just tried it again and it still works for me. Clearly it's something happening on your machine, such as a firewall setting.

**Comment by Jimrnelson** [comment]
@CHamlinPNP 

Is this still a problem?

**Comment by Jimrnelson** [comment]
@CHamlinPNP 

> Is this still a problem?

I am closing this issue as there has been no response in more than two months.
