### ISSUE TITLE
Problem installing from scratch

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#137]
## 📝 Provide detailed reproduction steps (if any)

1. pick empty folder
2. install as documented in https://github.com/VFPX/Thor/blob/master/Docs/Thor_install.md
3. start a plain VFP (no additional tools)
4. run Thor.app from the folder above

### ✔️ Expected result

Should install

### ❌ Actual result

Complains about missing `cthorlogforcfu` property

If one ignores the error multiple times, Thor will sooner or later run.

**Comment by Jimrnelson** [comment]
Rats!

Does the error occur if you run it again?

**Comment by lscheffler** [comment]
Only on first run on freshly downloaded Thor.

**Comment by Jimrnelson** [comment]
OK, thanks, that is very helpful

**Comment by Jimrnelson** [comment]
I have just released an update and the error does not recur for me.

Can you try again?

In the future, when getting a bug, can you include some of the debugger information?  Code with the error, call stack, local variables are always helpful.

Thanks.

**Comment by lscheffler** [comment]
It runs without error.   
- only it dates 2023/08/05

I really like to give better information about bugs. (Myself hates issues text like this) But this is Thor. It's all Execscript in Execsript, and all I see is the message that the debugger can not see the source code. There was even no pointer to the actual code line. I can try to sreenshot the debugger, but this one looked like it run into a secondary problem (error while logging an error). Would a screenshot be of help?

**Comment by Jimrnelson** [comment]
Odd that I got better information about the error when I reproduced it

The screen stack would have been helpful, actually, and locals, even if I could not see the code.

**Comment by lscheffler** [comment]
ok, I try to remember it. 

It would be a help if the template for the bug (.github/ISSUE_TEMPLATE/bug_report.md) hinting what you need.

**Comment by Jimrnelson** [comment]
I agree.

I think I would like a screenshot of the original error message, and also the trace,, call stack, and locals from the debugger:

**Comment by lscheffler** [comment]
Right now, the failure of this issue? Ooops. I will look if I can get the old version of the zip ...

**Comment by Jimrnelson** [comment]
No, this issue is closed.

I was responding to your comment about the bug report template.

**Comment by lscheffler** [comment]
see merge request
