### ISSUE TITLE
Thor doesn't generate SCX files

### ISSUE THREAD

**Issue by ViliusS** [VFPX/Thor#14]
I'm trying to install Thor.app, which I have downloaded from VFPX/Thor github repository, on a Visual FoxPro 9.0 SP2 (hotfixes included). The installation seems to go smoothly, Thor and Thor Tools menu. Update also works.

However then I try to launch Manage PRGS or other menus, nothing happens. The only two menus I can open is "Launcher" and "Config".

I've enabled Thor Debugging and saw that the code searches for SCX files, for example Thor_Tool_ThorInternalManagePlugIns.SCX, but these files are nowhere to be found in Thor folder.

Any suggestions?

**Comment by tbleken** [comment]
My suggestion is to restart your machine. If that doesn't help, try to re-install Thor. And make sure to follow the instructions carefully.

Tore Bleken

**Comment by DougHennig** [comment]
Did you install Thor Repository? Many of the Thor functions do not work unless you do.

Doug

**Comment by ViliusS** [comment]
Yes I did followed instructions carefully and restarted multiple times.

I cannot install Thor Repository because I cannot access Updates or Manage PRGs menus. All I can do is click on "Check for updates" which automatically does something but I cannot choose or see what's installed.

**Comment by ViliusS** [comment]
Any other suggestions? I tried with multiple computers now and I still cannot get Thor to work.

**Comment by KohrAhr** [comment]
about your FoxPro instance... what Operatation System do you have? Win7 or Win10? 32 bit ot 64 bit?

**Comment by ViliusS** [comment]
I use Windows 10 Enterprise 64 bit.

I just tried the following. Downloaded Thor Source. Extracted everything from Thor/Source/Procs and put it under C:\Program Files (x86)\Thor\Thor\Tools\Procs. Now I can view Check for Updates window and successfully update Thor and install other module.

Any ideas why non of the scx/sct files are installed during normal Thor installation? I could leave it as is, by I suspect others could have the same issue.

**Comment by KohrAhr** [comment]
as i know 64 bit OS causing a lot of issues. plz try to use 32 bit OS version

**Comment by tbleken** [comment]
@KohrAhr Your remark about 64-bit OS is simply not true. I have used 64-bit versions for ages, so far I haven't had any problems. I know others with exactly the same positive experience.  Be careful with spreading false rumors.

**Comment by ViliusS** [comment]
Well, I cannot believe I just needed to extract all contents from the downloaded Thor ZIP file in order it to work. My mistake was that I double clicked on Thor.app before full extraction.

Anyway, installation documentation needs to be improved https://github.com/VFPX/Thor/pull/15

**Comment by rschummer** [comment]
I wonder if the problem is related to installing the folder under Program Files (x86). VFP, unless running with administrative permissions might not be able to create things like FXPs (something Thor may have to do if the FXPs are not pre-compiled) and updating the tables Thor uses. All files under Program Files are protected by default unless you have altered the permissions or running VFP as administrator.

**Comment by DougHennig** [comment]
Rick, he found the issue: he only installed part of Thor. Once he did a complete extraction, it worked.
