### ISSUE TITLE
local update (My Updates)

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#142]
I'm not really sure on this, but.
I think, in older versions, I was able to place a prg in "Updates/My Updates" folder and that got precedence over "Updates" folder.   
Now it uses all the time from Update, and if I removed files on CFU it is replaced.

Do we have a chance to use the files from "Updates/My Updates" first? It would make testing much more easy if I do not need to change the id's

I try to resort a project, but this will not work this way.

Thank you.

**Comment by lscheffler** [comment]
Never mind, the problem must be on my side

**Comment by Jimrnelson** [comment]
@lscheffler 

The files in the "My Updates" folder are additional updaters to the ones normally available in Check For Updates.  There is no intent for them to replace the normal updaters.

There have been two uses for them that I am aware of:

1. For testing of new projects before they are publicly available in CFU.  This is what was done when Matt moved from GoFish4 to GoFish5, which resulted in some people having two distinct versions of GoFish available at the same time.
2. For testing of new features in existing projects.

In both cases, the PRG is distributed to any interested parties and only they will see them.  (They appear in italics in the CFU grid).

There is no provision for using this to automatically manage distinct versions of the same project.  That is left to the developer.

**Comment by lscheffler** [comment]
Ah, ok it's just the one on top and the other one. Fine, thanks.   

The eventlog just looks the same if the unzip fails 
[EventLog_fail.zip](https://github.com/VFPX/Thor/files/12283259/EventLog_fail.zip)   
or not
[EventLog_ok.zip](https://github.com/VFPX/Thor/files/12283276/EventLog_ok.zip)

Do you check the zip operation for return code?

**Comment by Jimrnelson** [comment]
I think it would help to clarify something here.

CFU does not unzip the file directly into its destination.  It actually does it in two steps:

1. It unzips it into a temp folder (checking the return code, I presume).
2. It then copies the contents of that temp folder to its destination.

You have reasonably been assuming that the error has been in step 1, unzipping, but that might not be the case.

There is some hint as to what's going in in the log file; see the extract below.  It appears that the zip worked but some use of NAMESPACE failed.  (I'll note here that I have no familiarity with NAMESPACE).

Note that you can browse the code by copying a file name from below (thor_proc_extractfilesfromzip) and using GoToDefinition to open it.  Perhaps you can discover what is happening.

19:03:36  Extracting from [D:\USERS\LUTZ\APPDATA\LOCAL\TEMP\Thor.CheckForUpdates.20230807.190311\Download_FoxBin2PRG_6OK14UN8P.zip] to [D:\USERS\LUTZ\APPDATA\LOCAL\TEMP\Thor.CheckForUpdates.20230807.190311\Download_FoxBin2PRG_6OK14UN8P]
						 thor_proc_extractfilesfromzip.prg, line 9
						 thor_proc_extracttopath.prg, line 16
						 thor_proc_downloadandextracttopath.prg, line 31
						 thor_proc_downloadandinstallupdates.prg, line 455
						 thor_proc_downloadandinstallupdates.prg, line 62
						 thor_proc_downloadandinstallupdates.prg, line 6

19:03:36  **Error extracting: Member NAMESPACE does not evaluate to an object.**
						 thor_proc_extractfilesfromzip.prg, line 21
						 thor_proc_extracttopath.prg, line 16
						 thor_proc_downloadandextracttopath.prg, line 31
						 thor_proc_downloadandinstallupdates.prg, line 455
						 thor_proc_downloadandinstallupdates.prg, line 62
						 thor_proc_downloadandinstallupdates.prg, line 6

**Comment by lscheffler** [comment]
The logs and the text above belong to #143, I just posted the logs on the wrong issue.

The logging for this issue was to find problems with errors in the URLs of the UPDATE prg's. The problems are unrelated so far.

**Comment by lscheffler** [comment]
@Jimrnelson, as Doug pointed out, I have the windows built in zip that allows file-system like access to zips (for example using them as folders) disabled, since I dislike this.    
Thor_Proc_ExtractFilesFromZip.PRG tries to open the zip in filesystem `loFiles = loShell.NameSpace(tcSource).Items`, this fails because of the setting. No namespace for ".zip", as it should be.

@DougHennig The `UnzipTo (tcDestinationPath)` will return .F. if the operation fails, but this is not handled. I have no idea how this works, so there is a need for some extra work to return it to the caller. I have no idea if there is more information available.

To solve the problem (with my setup, I guess most people will use the namespace ) would you mind to do something like
- putting archive and target to clipboard
- put something like "failure unzipping, please unzip ... to ..." to a messagebox
- and SET STEP ON so that I can unzip from desktop?
- and then a way to set a flag that I run successfully?
