### ISSUE TITLE
Problems unpacking thor zip

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#143]
I have problems unpacking a zip with Thor.

This is foxbin2prg, from my fork https://github.com/lscheffler/foxbin2prg/blob/fork_mod/ThorUpdater/FoxBin2Prg.zip,

I can see the zip in my temp folder, the zip contains all the files, only it does not expand completely.    
The file was created with VFPXDeployment.   
I can expand all files using 7z.   
Any ideas?

A Thor_Update prg is attached.

update
I zipped https://github.com/lscheffler/foxbin2prg/blob/fork_mod/ThorUpdater/FoxBin2Prg3.zip using 7z, and this is working

**Comment by lscheffler** [comment]
Why ever the updater was missing see here: [Thor_Update_FoxBin2PRG.zip](https://github.com/VFPX/Thor/files/12283135/Thor_Update_FoxBin2PRG.zip)

The problem happens while running CFU.
- I have a Thor installed from scratch
- Install the stuff mandatory
- Put the file from into "My Updates"
- Run CFU
- Install the FoyBin2Prg from top
- check the Components\FoxBin2PRG folder
- there is only a little files of the huge number in the zip
- checked the zip in my temp folder, found all files, expanded via 7z etc.

CFU gives no message at all, and I have no idea how to find a log are turn it noisy.

I created a new version of the zip ([FoxBin2Prg3.zip](https://github.com/lscheffler/foxbin2prg/blob/fork_mod/ThorUpdater/FoxBin2Prg3.zip)) with 7z instead of the way VFPXDeployment uses, and this expands all

----
conclusion:   
The problem my not CFU, only I get no message and see no way to trace it.

**Comment by Jimrnelson** [comment]
Is this issue still open?  Or is it part of #142?  

I'm no longer understanding what you're asking.

**Comment by lscheffler** [comment]
I beg your pardon. It looks like the issues are mixed now.    
The messages https://github.com/VFPX/Thor/issues/142#issuecomment-1668271211 and https://github.com/VFPX/Thor/issues/142#issuecomment-1668367405 belong to this issue (#143)

**Comment by Jimrnelson** [comment]
It’s still not clear to me if the unzipping is failing or if the copying of the files from the temp folder, is failing, as those are two separate stepsSent from my iPhoneOn Aug 8, 2023, at 9:59 AM, Doug Hennig ***@***.***> wrote:﻿
Thor_Proc_ExtractFilesFromZip.prg has two mechanisms to unzip files:


It uses Shell.Application first because there's a bug in VFPCompression.fll that fails to fully uncompress some files (which is what @lscheffler is running into). However, it doesn't work for @lscheffler because he has it disabled.


It uses VFPCompression if Shell.Application fails.


So, Shell.Application is failing for @lscheffler and then he's running into the VFPCompression bug.

**Comment by DougHennig** [comment]
@Jimrnelson I'm pretty sure it's the unzipping because I wrote the code using Shell.Application in response to the unzipping failing.

**Comment by Jimrnelson** [comment]
Ok I’m not looking at the code and can’t see where the error is happening.  Lutz could conceivably track that down to see exactly where.  But I repeat that there are two steps, one unzipping into a temp folder, the other copying those files into the destination.  So far I have not seen anything to indicate which is the failure point.  Lutz could look in the temp folder to see if all the files are there. Btw, am guessing that we have a Try/Catch that doesn’t report the error properly. Sent from my iPhoneOn Aug 8, 2023, at 11:18 AM, Doug Hennig ***@***.***> wrote:﻿
@Jimrnelson I'm pretty sure it's the unzipping because I wrote the code using Shell.Application in response to the unzipping failing.

**Comment by lscheffler** [comment]
I'm on a different problem right now, so I need some time to trace it.   
And, I think the file gets corrupted while packing - since the identical files packed with 7z unpack without problem.

**Comment by DougHennig** [comment]
@Jimrnelson I had tracked this down some time ago, and it's definitely in the unzipping not the copying. @lscheffler It isn't a bug in creating the zip file; it's a bug in VFPCompression unzipping it that I can reproduce: you can unzip the file using WinZip, Shell.Application, etc. but VFPCompression fails to extract all the files. That's what prompted me to write the part of the code using Shell.Application.

I don't know of any solution other than to manually unzip and copy the files. Fortunately, it affects very few projects and only those people that have Shell.Application disabled (only @lscheffler as far as I know from reports about problems).

**Comment by lscheffler** [comment]
@DougHennig You see the two files on top?   
The first one is packed with whatever VFPXDeployment uses (`Execscript(_Screen.cThorDispatcher, 'Thor_Proc_ZipFolder', m.lcInstalledFilesFolder, m.lcZipFile)`) the second one is created by 7z with the same files.    
I set up a clean Thor and run this.    
Then I just put the file from https://github.com/VFPX/Thor/issues/143#issuecomment-1668254129 into Thors "My Updates" and alter it later to download the other file.   
I install the foxbin2prg via CFU. The first fails, the second runs.

So it is not just unzipping. It looks like the VFPCompression- zipped itself has a problem that causes VFPCompression-unzip to fail, while 7z (and possibly the OS) will create a "better" file and ignoring the problem unzipping.

**Comment by lscheffler** [comment]
@Jimrnelson, as Doug pointed out, I have the windows built in zip that allows file-system like access to zips (for example using them as folders) disabled, since I dislike this.
Thor_Proc_ExtractFilesFromZip.PRG tries to open the zip in filesystem loFiles = loShell.NameSpace(tcSource).Items, this fails because of the setting. No namespace for ".zip", as it should be.

@DougHennig The UnzipTo (tcDestinationPath) will return .F. if the operation fails, but this is not handled. I have no idea how this works, so there is a need for some extra work to return it to the caller. I have no idea if there is more information available.

To solve the problem (with my setup, I guess most people will use the namespace ) would you mind to do something like

    putting archive and target to clipboard
    put something like "failure unzipping, please unzip ... to ..." to a messagebox
    and SET STEP ON so that I can unzip from desktop?
    and then a way to set a flag that I run successfully?

**Comment by lscheffler** [comment]
@DougHennig , @Jimrnelson 

The problem on CFU is mostly bound to problems packing, at least I see that the problem only raises with archives packed with VFPCompression.fll on my comp.   
If I compress with 7z, it runs pretty well (and fast). So I would like add code to Thor_Proc_ZipFolder, checking if 7z is on it's default location (C:\Program Files\7-Zip\7z.exe) and run this first from command line. If 7z os not found, just proceed as normal.   
One could do this to Thor_Proc_ExtractFilesFromZip.PRG as well.    

What's your idea about this?

**Comment by Jimrnelson** [comment]
@lscheffler @DougHennig 

Thor_Proc_ZipFolder is only used in VFP Deployment, so I see no reason to be concerned about conflicts.

I have no knowledge of the relationship between Zip and 7Z.  If a file is created with 7Z, can it be unzipped with Zip?  And vice versa?

**Comment by lscheffler** [comment]
@DougHennig 7z.exe can create normal zip (and a lot of other formats). 
It's faster then the Windoofs build in - and faster then the fll, but this no surprise.

I will add some code the the Thor_Proc_ZipFolder.prg to prefer 7zip over Windows over the fll.

The question is, should one do this to the Thor_Proc_ExtractFilesFromZip.PRG as well? The work is half done if the compression works, and it's faster, and for all not using 7z.exe it's just a IF FILE(... more.

It just solves the problem for me, while it is not a solution for everybody.

**Comment by Jimrnelson** [comment]
@lscheffler @DougHennig 

The problem I see with this is that not of all us running VFPX Deployment have or use 7Z.  (I don't).

For this to work, VFPX Deployment would actually have to require 7Z so that we all create zip files the same way.

BTW, which project is causing this problem for you and do you have any idea why it is just now doing so?

**Comment by lscheffler** [comment]
@DougHennig No, No, 7z should only create zip files here. It should not use it's own format. So the result is a normal zip file in any way. The solution does not **require** 7z.exe, just **prefer it if found**.

I'm working on FoxBin2Prg, I rebuild it to use VFPXDeployment, remove crap in the original zip and so on. I'm testing from my [fork]([https://github.com/lscheffler/foxbin2prg), and this fails to expand the zip file.

**Comment by DougHennig** [comment]
@lscheffler Are you going to add 7Zip support to Thor_Proc_ExtractFilesFromZip.PRG or should I?

**Comment by Jimrnelson** [comment]
A couple of questions before anybody does:

[1]  Are you requiring that anybody who uses VFPXDeploy uses 7Z?  I would certainly think that we should all be using exactly the same tools.  It sounds like 7Z fixed an otherwise unresolvable problem.

[2]  It sounds like it's necessary for zipping, but not so for unzipping.  So why bother?

**Comment by DougHennig** [comment]
I'm not suggesting changing VFPXDeployment. Instead, add another case to Thor_Proc_ExtractFilesFromZip.PRG: if Shell.Application fails, check to see if 7Zip is installed on the user's machine, and if so, use it to unzip the file. Otherwise, carry on with VFPCompression.

**Comment by Jimrnelson** [comment]
Sounds good.

**Comment by lscheffler** [comment]
@Jimrnelson 
#1 No. 7z is not a requirement at all, it's just an option more.
#2 We don't know. **I** think I nailed it down to failure for zip / unzip both with VFPCompression.fll in *this case*, but VFPCompression.fll is not reliable. So if I see a chance, I like 7z instead of VFPCompression.fll. And - it's faster then Windoofs or VFPCompression.fll. But thats why I ask.
  - If the the code to zip exists, it's not that tricky.

@DougHennig
- I'm on the way adding 7z support to Thor_Proc_ZipFolder.prg. 
- I use Ed Raus api_apprun to get the errorlevel from 7z, but until now it looks good.    
   - Should I add the class simply to Thor_Proc_ZipFolder.prg or should we put it to an extra prg? (or vcx, I use it in Bin2Prg)
- Could you alter the **UNZIP** to return errors from VFPCompression.fll?

@DougHennig to the latest message:   
My idea was
1. Try 7z (a simple `IF FILE(...` to check if we find it at default install location)
2. Try windows built in
3. Fall back to VFPCompression.fll

**Comment by Jimrnelson** [comment]
@lscheffler @DougHennig 

I am working on unrelated to changes to Thor as we speak.  I hope that they will go live later today.

Please hold off on any changes to Thor_Proc_ExtractFilesFromZip until I have done so.

**Comment by lscheffler** [comment]
@DougHennig It's 2300, no productive work at this time. Just some test that will result into it. :)

**Comment by DougHennig** [comment]
@lscheffler VFPCompression doesn't give an error: it just fails to do what it is supposed to. So there is no way to tell if it failed :(

**Comment by lscheffler** [comment]
@DougHennig This is not what I see. ` UnzipTo (tcDestinationPath)` in  *Thor_Proc_ExtractFilesFromZip* returns .F. if it fails to unzip my corrupted zip, .T. on success.

**Comment by lscheffler** [comment]
@DougHennig @Jimrnelson   
The VFPXDeployment thor_proc_zipfolder.prg procedure uses a powershell call to Compress.  

Possibly we should simply use this to unzip instead of `Shell.Application`, VFPCompression or 7z?    
If we use API_Run to execute it, we even get errorcodes back, so we can check success.   

This should solve all the problems.
- available independent of the use of zip folders
- ignore the bug of VFPCompression.fll
- no need for external tool like 7z

it's a bit slower then 7z, but his is a minor problem.

**Comment by Jimrnelson** [comment]
My only comment on this topic is this:  It better be bug free when Thor installs itself.

If Thor CFU bugs out when getting an update to Thor, then all of CFU is disabled.  Users' only recourse is to re-install Thor from scratch, and not all users will know how to do so and there is no way to communicate with them when the correction has been made.

This happened once, very early in the life of Thor, and was a major headache (at least at that time we had the Thor forum).

As for the specifics of which flavor of tool for zipping/unzipping is to be used, I have nothing to contribute.

**Comment by lscheffler** [comment]
@Jimrnelson I agree. I have a sand-boxed Thor for testing. It's gitted so I can reset fast, and I had some fun crashing it. It now looks like expanding is running for secondary runs of Thor, for a newly installed Thor there is still something odd.   

What do you think, would it be better to run the compress / expand in a visible window (like in VFPXDeployment) or hide it? i can see a value in both ...

**Comment by Jimrnelson** [comment]
I would not change the current behavior (not visible) unless there is a convincing reason to do so.

**Comment by DougHennig** [comment]
@lscheffler I would keep the current behavior of Thor_Proc_ExtractFilesFromZip (that is, using Shell.Application, then VFPCompression), and add a third option using PowerShell if VFPCompression fails. Because the first two work for most people for most projects, and we don't know if PowerShell might fail for someone, why introduce a potentially bigger problem by replacing all of the code with PowerShell?

**Comment by Jimrnelson** [comment]
> @lscheffler I would keep the current behavior of Thor_Proc_ExtractFilesFromZip (that is, using Shell.Application, then VFPCompression), and add a third option using PowerShell if VFPCompression fails. Because the first two work for most people for most projects, and we don't know if PowerShell might fail for someone, why introduce a potentially bigger problem by replacing all of the code with PowerShell?

I absolutely agree.

**Comment by lscheffler** [comment]
Since VFPCompression **is** faulty, I think
1. Shell
2. Powershell
3. VFPCompression

Powershell as such is reliable, there are enough users.

**Comment by Jimrnelson** [comment]
I would much prefer not changing this at all.  This problem has only arisen for Lutz, and then only in a very specific project.  I find it undesirable to make significant changes to handle this unusual case.

Instead I recommend that he make any desired changes and save them in "My Tools" and then this whole discussion goes away.

**Comment by lscheffler** [comment]
I prefer to use reliable tools on the place where they belong (what excludes both zip-folder integration to the OS as well as VFPCompression). And I surely disagree to such a kludge. I clearly see how this will fail on the next comp I set up in half a years time.   
It's very simply. Unzipping works, or the maintenance of the tools I work on could not include changes to it's Thor part, since I have no reliable way to test. It's a pain anyway. 

BTW, for this you should not use the  PowerShell approach in VFPXDeployment. ¯\_(ツ)_/¯

**Comment by lscheffler** [comment]
Since this seems to be a problem of me only, it's of no value any more.
