### ISSUE TITLE
Invalid Format in version file

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#145]
Thor Check for Update Giving error: Invalid Format in version file

Warm regards,
mk.
![thor1a](https://github.com/VFPX/Thor/assets/31514812/d59b596d-0eb8-4367-b403-9d5a4fe09166)

**Comment by mksharmamk** [comment]
resolved after deleting the file "ThorVersion.txt" from thor folder.

Warm regards,
mk.

**Comment by lscheffler** [comment]
Why ever it was wrong, CFU worked for my comp without problem.
