### ISSUE TITLE
Class definition TOOLS is not Found

### ISSUE THREAD

**Issue by griessbach14943** [VFPX/Thor#151]
Since the last but one update, my GoFish menu is no longer complete. 
I get the error "Class definition TOOLS is not Found" when calling the Finder. 
I also get this error within the app GoFish per dbl click in the resultgrid. 
Think the Collection thisform.oTools is not correct. 
Some menu items have also disappeared, so under GoFish all are gone except the Reset menu item.

![image](https://github.com/VFPX/Thor/assets/67592477/3bcbb65d-d8cc-43b5-8d2d-ad2c53ebb785)

Best regards 
Ulf Neugebauer

**Comment by Jimrnelson** [comment]
This seems to be a problem with GoFish, not Thor, and should be reported at [https://github.com/VFPX/GoFish/issues](url).

When you do, please note the following

> Since the last but one update

Are you referring to last update of Thor or GoFish?

> my GoFish menu is no longer complete. 

Please send a screenshot.

> I get the error "Class definition TOOLS is not Found" when calling the Finder. 

Please send a screenshot.

> Some menu items have also disappeared, so under GoFish all are gone except the Reset menu item.

Please send a screenshot

**Comment by griessbach14943** [comment]
I use 2 notebooks, the error is the same on both. I have found a workaround but it is not pretty. For example, after starting VFP, the menu of GoFish is incomplete.
![image](https://github.com/VFPX/Thor/assets/67592477/99bdd4a3-18c4-4b78-9031-89e32e5c3e4b)

If I now open the window for configuring Thor and close it again immediately without making any changes, everything works!

![image](https://github.com/VFPX/Thor/assets/67592477/ee29d263-6412-4b14-ba5d-6f11f6ef33b0)

The menu is complete again, all apps work.

![image](https://github.com/VFPX/Thor/assets/67592477/fb7c0cf2-4841-4f16-921e-db9d767fd4ab)

I am now closing VFP and restarting it. To show that there are not only problems with GoFish, I start Finder.

![image](https://github.com/VFPX/Thor/assets/67592477/65505c10-5d79-4ad8-bb26-cd6f0b7dd9d6)

See, there is the error.

![image](https://github.com/VFPX/Thor/assets/67592477/6f6546b7-31f9-449b-a6c0-040e4fc22e28)

**Comment by lscheffler** [comment]
@griessbach14943 What did you change to complete the issue, or did you touch the wrong button?

It would be nice to know what fixed it.

**Comment by griessbach14943** [comment]
Hello Lutz,
I didn't fix it, I think it's somehow the initialization of Thor. My workaround is to call the configuration window. After closing it, there is a refresh which makes everything work as it should.

**Comment by lscheffler** [comment]
Ulf, I'm not to deep into Thor, only the folks in the colonies have this time offset, and it's better you post now then later. I guess Jim will look at it. :)

**Comment by griessbach14943** [comment]
Hello,
I have identified the problem. A direct call to Thor.app leads exactly to this problem. I had specified it very "old school" without parameters as a startup program. I now start via RunThor.prg. 
I suggest to test in Thor.app for PCOUNT() = 0 to set the default settings "Run and .F.". 
Anlaog Do m.lcFolder + 'Thor.APP' With 'Run', .F. in the RunThor.prg.

Best regards
Ulf neugebauer

**Comment by Jimrnelson** [comment]
@griessbach14943 

Am so glad that's fixed and that you found the problem.  

Clearly, this would have been a hard one to diagnose from here.

I'm also glad for the time zone difference.  I's 6:30 here, and I was just reading your detailed message and wondering what in the world I could even ask to try to understand how you could see such odd behavior.

Lastly, thanks for your suggestion.
