### ISSUE TITLE
Problem while running git on different computers

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#152]
This why we saw the FoxBin2Text-text-files all changed on the pull request. Sry, it took some time to figure out the reason. Jim, thanks for the argument on the pull, it finally gave the hint.

Depending of the git Check-In-Check out settings, all text files are commited (for short) different on different computers and, even worst checked out. Either with LF or CRLF. This is why all *.??2 are rewritten even if there is no visible change. See https://github.com/VFPX/GoFish/issues/27#issuecomment-1308245572

We need to introduce **.gitattributes** file like we have for example in GoFish or in the https://github.com/VFPX/VFPXDeployment/blob/main/Source/Apps/VFPXDeployment/VFPXTemplate/R.gitattributes to project root and rewrite all text files.

@DougHennig Do you still have the code to rewrite a repo from 2022?

**Comment by DougHennig** [comment]
@lscheffler I don't think so.

**Comment by lscheffler** [comment]
The error or the code?

**Comment by lscheffler** [comment]
So this is the procedure we used November 2022:

- It's over-overkill, but a backup of the whole directory qualifies for mercy
- For each branch with an open end:
 1. switch into the branch
 2. clean the worktree.
   - Add all changed to git
   - commit
 3. copy, add and commit the .gitattributes file, if not already in the repo (this is, on each branch again!)
 4.  on bash, run
   `git rm --cached -rf .; git diff --cached --name-only -z | xargs -0 git add -f`
   (this will
    - delete from index
    - add all file cleaned back with line endings as newly specified)
 5. commit
 6. push, if it make sense to push

This must be done by somebody with the correct git settings, iow the value of
```
git config -l|grep autocrlf
```
must be true. (just run the command on bash)

What it does is:
- read the files from repository, change LF to CRLF as usual.
- tell git, that for this repository this translation should not happen, on no computer (by adding .gitattributes)
- clean up, and add all files git knows, even if git thinks they are untouched
  - this means store every CRLF as CRLF

---
In general I vote to set core.autocrlf true iow `git config --global core.autocrlf true`, or while installing git there is a page about line endings, the option *commit as is, checkout as is*.   
Until one is coworking with 'nix type OS. The whole thing is made to keep 'nix files as 'nix files while working them under (Win)DOS. (IOW: turn the LF to CRLF for DOS while checkout so ancient DOS editors can work it, and back while commiting). There is no sense if one only  uses DOS and in special not for VFP

The .gittatributes file just overrides git settings (global, system or local) wherever the repository is used.   VFPXDeployment will add this file with community option on.

**Comment by Jimrnelson** [comment]
Am late to the party here.

What problem is this trying to address?

**Comment by lscheffler** [comment]
line endings havoc

git has a feature to change line endings from CRLF to LF when adding from workdir to index and from LF to CRLF on commands putting files into the workdir.   
Why, see above, how to test your system, see there too

Now, some systems are set up that way, and others just to keep the line endings. There is a option while installing git one need to know what the question means.

Somebody, you (for simplicity, we use you in the following), Doug, who knows, is operating git with the conversations. Others, me for example, keeping line endings.

- you edit a textfile, with CRLF
- git will store with LF.
- you push, I pull
- I checkout, **keeping LF**
- I run FoxBin2Prg, writing files from scratch **with CRLF**
- I run `git add .` - git compares, does not convert to LF, see the files differ and adds them,
- BINGO all lines are changed - while all between line endings is identical

We had some fun with the LF , see the link to GoFish

So, the basic idea - one should do for any repository that might run on strangers comp - is telling git to use one option only **for this repository, independent of the comp**.

This is done with .gitattributes file, and we use the **keep** option, since we know how to do this.

The code algorythm above just gets all files, auto-convert to CRLF, add the file and forces git the reared any file.

It's a good idea to do this to all repos one own.

**Comment by DougHennig** [comment]
All done.

**Comment by Jimrnelson** [comment]
Can we mark this as complete?

**Comment by Jimrnelson** [comment]
> All done.

And thus I am closing this issue.
