### ISSUE TITLE
Gofish not showing Properly in Thor Tools when Thor start 

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#153]
Gofish not showing Properly in Thor Tools when Thor start 

Thor Tools->Applications->Gofish   && Showing only 2 options as Image attached.

and after Running Thor->Configure(Alt+F12) .... Now it is showing the 4 Options

Warm regards,
mk.

![thor1b](https://github.com/VFPX/Thor/assets/31514812/48740162-70fc-474c-98ee-21da95c31f64)

![thor1c](https://github.com/VFPX/Thor/assets/31514812/03e2f508-e8e4-417f-b1b2-0418489c818f)

**Comment by lscheffler** [comment]
@mksharmamk    
Please close and repost at https://github.com/VFPX/GoFish/issues.   
Please add **there**:
- Is GF installed via Thor?
- Was GF changed with an run of CFU (Thors update check)?
- Do you run GF via Thor or external?
- This is the latest of GF?

**Comment by lscheffler** [comment]
@Jimrnelson What code in GF is called by Thor->Configure(Alt+F12) (iow what interface)

**Comment by Jimrnelson** [comment]
@mksharmamk   @lscheffler 

> Please close and repost at https://github.com/VFPX/GoFish/issues.

No, please do NOT report this problem on the GoFish page..  This is entirely a Thor problem and belongs in this forum.

The problem has to do with how Thor is creating its menu pad.  

It just turns out that the problem reveals itself for GoFish.  

It may be happening for other tools as well, it's just that they haven't been reported.

**Comment by Jimrnelson** [comment]
> @Jimrnelson What code in GF is called by Thor->Configure(Alt+F12) (iow what interface)

None.  Alt+F12 just opens the main Thor configuration screen.

![image](https://github.com/VFPX/Thor/assets/81179335/a959996a-1d35-47fb-988f-f7142c656e2f)

When that screen closes, even if you haven't done a thing, it re-creates all menus and hot keys, which (somehow) resolves the problem.

As indicated in my previous post, this is a problem in Thor and not GF.

**Comment by Jimrnelson** [comment]
@mksharmamk 

mk -- Hey, nice to hear from you again and knows you are still active as well!

This is an odd problem, but one that was also reported earlier this week.   The dev who reported that problem resolved it himself by changing how he calls Thor, by using `RunThor`.

How do you invoke Thor in your session?

**Comment by mksharmamk** [comment]
I have a "MyStart,prg " with below code
*MyStart.prg
Do Home()+'thor\thor.app'

Tools->Options-File Locations
Startup Program = c:\vfp\mystart.pg

Warn regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

mk --

Well, that should work, but for reasons that are beyond me, doesn't work any more.  Try this, instead:

`Do Home()+'thor\thor.app' with 'Run'`

This is one of those odd cases where I am not aware of changing anything related to this in a long long time, but suddenly it's mis-behaving.

Beyond that, it makes no sense to show some tools but not all.

So, I am assuming this will not be an easy one to track down.

In any case, I hope my little fix above handles the problem for you.

**Comment by mksharmamk** [comment]
Thank you Sir,
Working Perfect!

Warm regards,
mk.

**Comment by lscheffler** [comment]
Ah, the `Thor\RunThor.prg` does this internally. :)

**Comment by Jimrnelson** [comment]
mk --

Glad that was such an easy fix on your end.

On my end, I still do not have much of an idea why this suddenly stopped working (but only partially).  It might help me if you could paste in the Tool for GoFish, which you can open like this:

`Modify Command  _Screen.cThorFolder + "Tools\THOR_TOOL_GOFISH5.PRG"`

Cheers from sunny Southern California!

**Comment by mksharmamk** [comment]
Is you need content of  "Tools\THOR_TOOL_GOFISH5.PRG" file?
Warm regards,mk.

    On Saturday, 19 August 2023 at 07:35:09 pm GMT+5:30, Jimrnelson ***@***.***> wrote:  
 
 


mk --

Glad that was such an easy fix on your end.

On my end, I still do not have much of an idea why this suddenly stopped working (but only partially). It might help me if you could paste in the Tool for GoFish, which you can open like this:

Modify Command _Screen.cThorFolder + "Tools\THOR_TOOL_GOFISH5.PRG"

Cheers from sunny Southern California!

**Comment by Jimrnelson** [comment]
Yes, I believe that might be helpful.  Thanks.  Sent from my iPhoneOn Aug 19, 2023, at 10:12 AM, mksharmamk ***@***.***> wrote:﻿
 Is you need content of  "Tools\THOR_TOOL_GOFISH5.PRG" file?

Warm regards,mk.



    On Saturday, 19 August 2023 at 07:35:09 pm GMT+5:30, Jimrnelson ***@***.***> wrote:  

 

 





mk --



Glad that was such an easy fix on your end.



On my end, I still do not have much of an idea why this suddenly stopped working (but only partially). It might help me if you could paste in the Tool for GoFish, which you can open like this:



Modify Command _Screen.cThorFolder + "Tools\THOR_TOOL_GOFISH5.PRG"



Cheers from sunny Southern California!

**Comment by Jimrnelson** [comment]
@mksharmamk @griessbach14943 

I believe I have corrected a problem that both of you reported where GoFish was not showing properly in your "Thor Tools" menu.  This is fixed (I think) in today's update, 1.46.02.

Each of you changed your code that called Thor.App without a parameter.  I believe that your old code (no parameter to Thor,App) should work correctly now.

**Comment by mksharmamk** [comment]
Thank you,Gofish Menu showing proper with the latest thor.app Update.
Do Home()+'thor\thor.app'  


Warm regards,mk.

    On Sunday, 20 August 2023 at 03:16:52 am GMT+5:30, Jimrnelson ***@***.***> wrote:  
 
 


@mksharmamk @griessbach14943

I believe I have corrected a problem that both of you reported where GoFish was not showing properly in your "Thor Tools" menu. This is fixed (I think) in today's update, 1.46.02.

Each of you changed your code that called Thor.App without a parameter. I believe that your old code (no parameter to Thor,App) should work correctly now.

**Comment by Jimrnelson** [comment]
Thanks for the confirmation of the bug fix.  One of those odd ones were the solution was to move a line of code.

**Comment by lscheffler** [comment]
Mir fehlen die Worte.

In this case I need a window the create the pull request.
