### ISSUE TITLE
Thor Error

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#165]
Some times Giving Error as below image when "Do Thor.app"

![image](https://github.com/VFPX/Thor/assets/31514812/712ff4ac-795d-4258-960d-702bf22a9904)

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

This may occur if you are running Check For Updates in a session that you have been working in for some time.

The recommendation is to run Check For Updates as early as possible in a session.

**Comment by mksharmamk** [comment]
Thank you,
This issue resolved in Version 1.46.06

Warm regards,
mk.
