### ISSUE TITLE
Any Hot Key Thor Tool

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#167]
Any Hot Key Thor Tool for assign the HotKey like: Shift+Ctrl+A, Shift+Ctrl+B, Shift+Ctrl+C, Shift+Ctrl+D
Hot key for Inventory Software menu.

Shift+Ctrl+A  for Sales Form
Shift+Ctrl+B  for Purchase Form
Shift+Ctrl+C  for Sales Return Form
Shift+Ctrl+D  for Purchase Return Form

Warm regards,
mk.

**Comment by tbleken** [comment]
Note that Thor is only meant for use in the IDE, not in an end user application.

Tore Bleken

From: mksharmamk ***@***.***>
Sent: lørdag 30. september 2023 09:54
To: VFPX/Thor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VFPX/Thor] Any Hot Key Thor Tool (Issue #167)


Any Hot Key Thor Tool for assign the HotKey like: Shift+Ctrl+A, Shift+Ctrl+B, Shift+Ctrl+C, Shift+Ctrl+D
Hot key for Inventory Software menu.

Shift+Ctrl+A for Sales Form
Shift+Ctrl+B for Purchase Form
Shift+Ctrl+C for Sales Return Form
Shift+Ctrl+D for Purchase Return Form

Warm regards,
mk.
