### ISSUE TITLE
Thor UtifyX.prg in menu

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#178]
Thor UtifyX.prg in menu as below image ?

![image](https://github.com/VFPX/Thor/assets/31514812/e611899b-ae3e-440d-8e19-9d7ec9e685fb)

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

I don't think Thor did that, as it does not create any new menu pads on its own. 

My guess is that it is something you did inadvertently in Thor Configuration.

Open Configuration (Alt+F12) and you should be able delete it.

**Comment by mksharmamk** [comment]
I have Hotkey Shift+Ctrl+B  for BeautifyX 
When I Start VFP, open a prg file and Press Shift+Ctrl+B **First time** then it open the "Thor Configuration" form and create this menu item automatically.

Warm regards,
mk.

**Comment by mksharmamk** [comment]
It happen only first time.
Do Home()+'thorinstall\thor.app' 

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

In order for me to track this down, it would be very helpful if you answered **all** my questions.

By the way, calling Thor.App without parameters is used for the initial installation of Thor.  

I suggest you use RunThor.PRG instead (found in the same folder as Thor.App). 

I have no idea whether this is related to the problem you are reporting, but then again I have no other ideas on the possible cause either.

**Comment by mksharmamk** [comment]
Thor.App and RunThor.prg  not in Same Folder.
Thor.app Location C:\vfpa101\ThorInstall\Thor.App
RunThor.prg  Location C:\vfpa101\ThorInstall\Thor\RunThor.prg

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
Use it anyway

**Comment by Jimrnelson** [comment]
I believe that this problem is resolved, so this issue can be closed.

Re-open it if it happens again.
