### ISSUE TITLE
don't use gofish!

### ISSUE THREAD

**Issue by grkncl** [VFPX/Thor#18]
issue moved to related repo https://github.com/mattslay/GoFish/issues/9

**Comment by mattslay** [comment]
This bug has been fixed in GoFish 5.0.164 ... See closed issue #9 in the GoFish repo: https://github.com/mattslay/GoFish/issues/9

I am working with the VFPx Team leaders to get the updated released via Thor Check For Updates.

**Comment by mattslay** [comment]
As of 2021-03-24, Thor Updates will pull down the latest version of GoFish, which has this reported bug fixed in Version 5.0.164 and later.
