### ISSUE TITLE
Installing Quick Access menu broke Thor

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/Thor#183]
## 📝 Provide detailed reproduction steps (if any)

1. Thor's been running on this machine for a long time.
2. Just installed the new Quick Access menu
3. Thor no longer works. specifically, whatever I try, I get "File 'thor.app' does not exist." or in some cases, "File 'D:\Fox\VFPX\Thor\Thor.App' does not exist.

### ✔️ Expected result

Things work

### ❌ Actual result

The error above. What appears to have happened is that it's expecting to find Thor.app one level up from where it's installed. That is, I have Thor in D:\Fox\VFPX\Thor\Thor, but it's looking in D:\Fox\VFPX\Thor. 

## 📷 Debugging Info
Program Error
Cancel
Suspend
Ignore
Help
File 'D:\FOX\VFPX\THOR\Thor.App' does not exist.

**Comment by TamarEGranor** [comment]
Looking a little harder, my diagnosis of what's wrong seems to be incorrect. Looks like Thor.App is missing.

I installed the Quick Access menu and then I went to check for updates. That process failed, and I blamed it on Quick Access menu, but maybe it was something else. I can no longer run Thor on this machine, so I can't recreate without deleting the whole thing and starting over, which I really don't want to do. Some guidance would be appreciated.

**Comment by Jimrnelson** [comment]
@TamarEGranor 

Ah, so CFU failed?  Do you know what happened, how it failed?  That would have been helpful.

To recover, you don't have to completely re-install.  Start with the first step of downloading the zip and unzipping it into some temp folder.  That should give you Thor.app that you can put back in place.

This is a new one, BTE, and I have no idea how what file could have been erased.  

Let me know how it goes.

**Comment by TamarEGranor** [comment]
Pulled Thor.App right from the zip into the folder it belonged it and that fixed it. Now I'll run CFU again (which I was doing to find Pandora during Tore's session). And this time, it ran without a problem. My vague memory is there was some kind of problem unzipping the first time, but I didn't catch what it was. So I'll close this since clearly, what I reported was not what was actually wrong.

**Comment by Jimrnelson** [comment]
@TamarEGranor @DougHennig 

Tamar --

Thanks for re-visiting this and identifying where the real error occurred, in CFU.

The recommended way to run CFU is at the beginning of a session.  Realizing that people may not always do that, Doug tried a fix (two years ago) to remove Thor.App before installing Thor.  However, if the download of Thor crashed, you would be left without Thor.App.  That's what happened.

I have tried a different approach to resolving this problem with today's Thor update.  We'll see if there's ever another report.
