### ISSUE TITLE
Show Help is broken

### ISSUE THREAD

**Issue by fcwaud** [VFPX/Thor#184]
## 📝 Provide detailed reproduction steps (if any)

1. …Clicked on Thor Tools; Tables 
2. …Pressed Shift and clicked Super Browser and chose Help from the popup

### ✔️ Expected result

I was expecting the help to open

### ❌ Actual result

Got a "File not found" error 

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots
Are there any other us
![Thor error](https://github.com/VFPX/Thor/assets/36264691/a1a66984-44c3-4da7-b63e-83fe518b1e21)
eful screenshots? WinKey+Shift+S and then just paste them directly into the form.

**Comment by Jimrnelson** [comment]
@fcwaud 

Can you reproduce that error?   If so, can you please include screenshots of the local variables and call stack as well, that will help with diagnosis.

Thanks / Jim

**Comment by fcwaud** [comment]
i just tried it again, and it worked fine. Not sure why I was having trouble yesterday. I will let you if it happens again, and I will include all the extra info you asked for (I should have done that yesterday).

**Comment by Jimrnelson** [comment]
@fcwaud 

[1]  Glad this worked for you, eventually

[B]  The trouble you had yesterday was that the "Help" code experienced an unexpected condition and thus did not handle it gracefully.

[Gamma] This should be fixed in the next CFU update to Thor Repository.

[Zed] Glad to see you're taking advantage of what you learned from my sessions.

/ Jim

**Comment by fcwaud** [comment]
Hi Jim

I think the problem was that I ran this on a Windows 2008 Terminal server. We use that one for FPW development, and we also have a Windows 2016 server for VFP development.

I have been trying to get Thor installed for a few years, but every time I tried, it gave errors and failed. Tamar and Doug both tried to help but we were never successful. That is until yesterday. I tried it on the 2016 server and it installed perfectly.

Since then, I have been exploring and learning whenever I had time between sessions.

When I got that error with the help yesterday, I debugged and saw that in thor_proc_showtoolhelp.prg it assigned the name of a path/file to a variable and then ran a download command with that:
      lcDestFile = Addbs(Sys(2023)) + Sys(2015) + '.Directory.txt'
      llSuccess  = Download(m.lcContentFolder + 'Directory.txt', m.lcDestFile)

The problem was that llSuccess was .f., but the code went on and issue this command:
      lcDirectory = Filetostr(m.lcDestFile)

which failed – see screen shot below

Anyway, I’m ok now, but I thought you might want to see this.

Thanks
Charles

***@***.***




Note - If you are looking for WaudWare tech support, either press F1 in PICS and search the PICS Help system or email ***@***.******@***.***> instead of, or in addition to my email address

F. Charles Waud
General Manager, WaudWare Incorporated<https://www.waudware.com>, a wholly-owned subsidiary of GrubMarket, Inc
Phone:  (905) 846-9737 ext 555  •  Toll Free:  (855) 742-7776  •  Fax:  (905) 846-9738

For the latest news on our PICS Software, please subscribe to our Blog at https://www.produceinventory.com/blog/.

**Comment by Jimrnelson** [comment]
@fcwaud 

Hey, very helpful indeed.  Today's update to Thor tries to rectify this problem by using the value of llSuccess to try again.

This is one of those errors that's impossible to reproduce, of course, so my bug fix is just an educated guess.

**Comment by fcwaud** [comment]
Actually, I can confirm it is fixed.

Using my existing version on my 2008 server, I tried it again and it failed in the same way I reported. Then on my 2016 server I did the check for updates, and after that, tried again and the problem was gone. I got a popup window with some info about SuperBrowse.

When do the same process on my 2016 server, it opens a browser and takes me to the help. So the behavior is different, but there is no error.

Thanks for sorting this out

Chas


Note - If you are looking for WaudWare tech support, either press F1 in PICS and search the PICS Help system or email ***@***.******@***.***> instead of, or in addition to my email address

F. Charles Waud
General Manager, WaudWare Incorporated<https://www.waudware.com>, a wholly-owned subsidiary of GrubMarket, Inc
Phone:  (905) 846-9737 ext 555  •  Toll Free:  (855) 742-7776  •  Fax:  (905) 846-9738

For the latest news on our PICS Software, please subscribe to our Blog at https://www.produceinventory.com/blog/.
