### ISSUE TITLE
Manage plugns error

### ISSUE THREAD

**Issue by rikaye** [VFPX/Thor#185]
Inspired by Jim's SWFOX sessions, I decided to do a fresh install of Thor. (My original install was years old and there was an accumulation of cruft I just couldn't figure out how to get rid of.) 

Summary:
I renamed the old folder and then installed the latest according to the standard instructions. 
I checked for updates and pulled the Thor repo and PEME.
Restarted VFP and checked for updates; installed a bunch of stuff..
Restarted VFP one more time.

## 📝 Provide detailed reproduction steps (if any)

1. Click Manage Plugins from the main Thor menu.

### ✔️ Expected result

Load the Mange Plugins form.

### ❌ Actual result
Error thrown; form does not appear.

## 📷 Screenshots
Error dialog
![image](https://github.com/VFPX/Thor/assets/28717887/21a494d9-9344-420f-8d42-20a059685668)

Debugger
![image](https://github.com/VFPX/Thor/assets/28717887/cfc65fba-290f-42de-a143-e5e1600994d9)

Locals
![image](https://github.com/VFPX/Thor/assets/28717887/cdaa1e8b-da6f-4380-8c44-e8512d105bbe)

One related note; there is no PluginsPRG.dbf in the tables folder. I assume this gets created on the fly the first time but have not yet had the time to go through the code to try and figure that out,

**Comment by Jimrnelson** [comment]
@rikaye 

Am so glad I have provided some inspiration!

Also, thanks for detailed debugging info.  Unfortunately, as you know, there are always more questions.

* In your environment,  does PEMEditor open properly for you?

* Can you execute the following line?  I think it will return Null for you (oops!)

     `?ExecScript(_Screen.cThorDispatcher, 'ToolInfo=', 'Thor_Tool_Pemeditor')`

* Can you execute the following line?  I am hoping it returns an object

     `?ExecScript(_Screen.cThorDispatcher, 'ToolInfo=', 'Thor_Tool_PEME_LaunchPemeditor')`

**Comment by rikaye** [comment]
Thanks, Jim. As someone with clients in multiple locations worldwide I very much understand how a decent issue report makes both my life and my client's lives better, and I appreciate the appreciation. :-) 

Good question; I had not yet run PEME. Just did.

PEME screenshot
![image](https://github.com/VFPX/Thor/assets/28717887/b20bda51-0b49-4cf6-9938-bec730304be3)

EXECSCRIPT results
![image](https://github.com/VFPX/Thor/assets/28717887/9bfc617e-a149-445b-b49f-f1597a188565)

Let me know what you need next. Thanks!

**Comment by rikaye** [comment]
Hi Jim,

Conference over; hanging around at the hotel and thought go check for updates. :-) Manage plugins coming up.

**Comment by Jimrnelson** [comment]
Let's close this one out.
