### ISSUE TITLE
Unable to install thor

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#188]
Unable to install thor and Thor.App Deleted auto ?

![thor1d](https://github.com/VFPX/Thor/assets/31514812/f8fe28ec-3a05-4c94-ac1f-1c9910c537a7)

If we Run Check for Updates Again then below error

![thor1e](https://github.com/VFPX/Thor/assets/31514812/a6dd0f1f-f4a5-43a3-8e05-1d7af4fefb3f)

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

Try this:

1. [Download current version of Thor](https://github.com/VFPX/Thor/archive/master.zip).
2. Unzip the file into some temp folder.
3. Copy Thor.App from that temp folder into the folder where you had installed it before.

I believe that this will correct the problem.

**Comment by mksharmamk** [comment]
Thank you,
Problem solved after copy the latest Thor.App in thor install folder.

Warm regards,
mk.
