### ISSUE TITLE
Duplicate hotkey labels showing on Quick Access menus

### ISSUE THREAD

**Issue by Steingo** [VFPX/Thor#191]
## 📝 Provide detailed reproduction steps (if any)

1. …Install Quick Access from Thor Launcher
2. …Open the QA menu
3. …

### ✔️ Expected result

What is the expected result of the above steps?
Should see the actual hotkeys

### ❌ Actual result

What is the actual result of the above steps?
Instead see some real keys, but bogus duplicate labels in others
## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots
Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form.
![thorqa](https://github.com/VFPX/Thor/assets/38174426/b48b35a0-5a23-427a-89bc-6c7f98236c76)

**Comment by Steingo** [comment]
It appears that if an option has an actual HK it is displayed correctly.  The duplication happens if the subsequent options do not have pre-assigned keys.  In the above example, it shows the correct keys for GoToDef and Finder.  But it duplicates the Ctrl-D from GTD for the next 3 items.  I see the same pattern in other dropdowns.  Under Windows Mgmnt, I have the Cycle Thru option set to Alt-R, which is properly displayed, but it then shows Alt-R for 4 of the following 5 items (which do not have hotkeys assigned).
Note that in some cases (such as the last 2 items above) it correctly shows the item as having no hot key.

**Comment by Jimrnelson** [comment]
@Steingo 

See #192 (Mangled Hot Keys in Thor)
