### ISSUE TITLE
Folder in use error during PEM update

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#2]
Used 'Check for updates' to get latest version of PEM installed.
Thor found and downloaded the latest.
During install, however, I get a "...action can't be completed becuase the folder or a file in it is open in another program" error. No details available, so I have no idea what's causing the heartburn.
Doesn't matter if PEM is open or closed at start of process.

**Comment by DougHennig** [comment]
It sounds like PEMEditor.app may be open. Try starting up VFP, then immediately choose Check for Updates from the Thor menu.

**Comment by BobWilkes** [comment]
Possibly. I start PEM Editor via 'Startup?' checked in Thor Configuration, Startup Tools tab.
After startup, Disp Memo shows _OPEMEDITOR
If I close the PEM DIalog, _OPEMEDITOR is still in memory.
If I specifically release _OPEMEDITOR, the update still fails.

I unchecked the Startup entry, restarted VFP, and checked for updates.
AOK UNTIL 'File is in use' Error in Thor_Engine OpenTable:
  Case Pcount() = 1
->    Use (lcFolder + tcTableName) Shared Again in 0

        lcFolder = "C:\PROGRAM FILES (X86)\VFP9\Thor\Tables\"
        tcTableName = "MenuTools"

Problem is MenuTools ISN'T OPEN, i.e., Used('MenuTools') = .F.; only HotKeyDefinitions and MenuDefinitkions tables are open.
Perhaps it's a Data Session issue?
?Set('DataSession') = 6
Hope this info helps...

**Comment by DougHennig** [comment]
I can't reproduce this so it'll be very difficult for me to track it down. You may have to trace the code to see what's happening.
