### ISSUE TITLE
Thor.app parameter of "Help"

### ISSUE THREAD

**Issue by rschummer** [VFPX/Thor#20]
DO "THOR\Thor.APP" with "Help"

Brings up CodePlex archive: https://archive.codeplex.com/?p=vfpx

It would be better if it brought up: https://github.com/VFPX/Thor/tree/master/Docs

Actually, searching the Thor project file shows 12 lines of code with CodePlex references.

Rick Schummer

**Comment by DougHennig** [comment]
Fixed in Thor 1.43, which I'll push once the Thor Updater process has been fully tested
