### ISSUE TITLE
Background of Thor update messages is dark blue

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/Thor#200]
## 📝 Provide detailed reproduction steps (if any)

1. Run Thor CFU (when there's some update available)

### ✔️ Expected result

Messages would be easily readable

### ❌ Actual result

Messages that appear have black text on a dark blue background. It's non-standard and hard to read. This has been going on for a few weeks, but I haven't been quick enough to grab a screenshot.

**Comment by Jimrnelson** [comment]
Fixed in today's update.
