### ISSUE TITLE
Information on Install CFU screen / Links

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#209]
## 📝 Provide detailed reproduction steps (if any)

1. Get vanilla Thor
2. Run Thor

![grafik](https://github.com/VFPX/Thor/assets/27769909/65285a29-2cd9-41f9-bd42-dfa4a2b6a0d8)

3. Uncheck the three topmost / yellow items
  - what the heck do I need *Dynamic Forms* for? Dependency? Then say so, somewhere on the form. I do not not need or want it for myself.
  - From where do they update anyway? They are not installed yet.
5. Click *Install Updates*
6. Run CFU again

![grafik](https://github.com/VFPX/Thor/assets/27769909/3081f468-74d8-4fc3-bd2c-faa323513425)

Didn't I say **No**? Dear code, either you do not ask, or you do what I say. Possibly I dislike to have it installed and no use of it at all? I can not even disable it, because the magic folder allowing this is not existing yet??   
BTW, Thor itself is not updated, during this process (first run). Seams to have more then one idea what to do.

----
It is more then surprising to click into the "Installed Version" column and open a web browser. The second column at least is underlined and gives a hint , but clicking an empty cell raising the browser is unusual. Also it is the logical target to select a row - it's the biggest column. And it does not link to a specific version, but to the same as the second column. Strange.
BTW, good interfaces ASK if the user allow like to raise a browser window. 

----
I have complained about "Recently updated" for stuff I have not installed before. Also GoFish is not **new**. Might be a new version. But not a new module.
Anyway, to mix up the state on the comp (*Current* for the three unwanted items, *Not installed* below) and the state somewhere in heaven (*New Project*, *Recently updated*) in one column is misleading. Couldn't be that big a problem to split it into two columns?

**Comment by Jimrnelson** [comment]
First things first --

You raise a number of topics here.  They should be in separate threads.  It's a mess to try to respond to otherwise.
