### ISSUE TITLE
Repository for Thor is not responding

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/Thor#21]
Every time I try to run Thor I get the following: URL cannot be opened. Then if you try to check for updates you get: Requesting file _ThorVersionFile.txt from server...it tries it several times...it finally gives up and again says URL cannot be opened and then pops up with Error getting available version information from server.Thor.App...URL: http://vfpxrepository.com/dl/thorupdate/thor/_ThorVersionFile.txt

If I try to manually go to that URL from a browser it just says that it did not respond with any data.

Is the repository no longer available?

**Comment by DougHennig** [comment]
I'm not sure what the issue was but it's working now.
