### ISSUE TITLE
Baseform alters environment, but does not reset.

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#210]
## 📝 Provide detailed reproduction steps (if any)

1. open a Thor form
2. close the form

### ✔️ Expected result

Nothing of SET or SYS should be altered

### ❌ Actual result

SYS(3054) is turned off

## 📷 Debugging Info
baseform.LOAD modifies SYS(3054), but closing the form does not reset.

**Comment by Jimrnelson** [comment]
Fixed in Thor 1.46.17 - Released 2023-12-16
