### ISSUE TITLE
Thor does not update itself while  run the first time.

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#212]
## 📝 Provide detailed reproduction steps (if any)

From  #209, #205

1. Install an older vanilla version of Thor, for example [this](https://github.com/VFPX/Thor/tree/79fd65aebe106c150e5bf2b5f5bda4e9ad9c6d68), 
2. Run

### ✔️ Expected result

Thor updates itself and runs CFU to install modules,

### ❌ Actual result

Only install modules. To update Thor itself it needs a second run of CFU.

### Remark
Sure, one can do the adventure to download fresh "Install" via github. Anyway, Modules should fit the version of Thor as good as possible. I just imagine to have the old unpacker and expect it running. And then starting a new issue about it. 

### Site note
It would be helpful to have recent version and release date of Thor visible in CFU form, just like in the *Thor Configuration* form.

**Comment by Jimrnelson** [comment]
Yes, if you choose not to follow standard installation instructions for Thor, you may encounter undesirable results.

But that is not Thor's problem.

**Comment by lscheffler** [comment]
https://github.com/VFPX/Thor/issues/96#issuecomment-1830981628
