### ISSUE TITLE
Information on CFU is not clear

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#213]
## 📝 Provide detailed reproduction steps (if any)

From  #209   
This is more then one single item, because this is one single problem out of a lot stuff. Must be seen together. If one does atomic issues, one need to jump between those issues.

1. Get vanilla Thor
2. Run Thor
3. Run CFU later on

![grafik](https://github.com/VFPX/Thor/assets/27769909/65285a29-2cd9-41f9-bd42-dfa4a2b6a0d8)
![grafik](https://github.com/VFPX/Thor/assets/27769909/3081f468-74d8-4fc3-bd2c-faa323513425)
### ❌ Actual result

The column "Status" mix up the state on the comp (*Current* for the three unwanted items, *Not installed* below) and the state somewhere in heaven (*New Project*, *Recently updated*) in one column. This should be two columns.   

Or if you say that the *Installed Version* column shows the computers status, then
- "Not installed" is doubled. Just use this text instead empty on "Installed Version"
- The picture on top shows to *Update* a not installed module.
- If one select an additional module on first run, the "mandatory" modules show **Install now** while the others just keep whatever is there.  Confusing. (Again, that there might be some logic in the words, it's not an intuitive one. In special for somebody not native to English.)

- "Recently updated" is "(older) Update available".
- "New Project" is wrong as it goes. GoFish6 is not a "New Project". It might be "New Update available"

- On a fresh install, all is simply "Not installed". There is nothing "New" or "Updated".
- The "(...) Updated" information belong to modules that are installed only. 

- The *Update* column is Update or Install. Works on guess only.

- Whatever the colours mean, there is no kind of hint on the whole form. It seams to double up some information given by "Status" column?

**Comment by Jimrnelson** [comment]
The CFU screen has been modified to include some of these suggestions.
