### ISSUE TITLE
Raising web browser from CFU

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#214]
## 📝 Provide detailed reproduction steps (if any)

From  #209  

1. Run CFU
2. Click "Application / link .." or "Installed Version"

### ✔️ Expected result

- Click should select the row.
- DoubleClick on "Application / link .." opens the link

### ❌ Actual result

Raises web browser

### Remarks
It is more then surprising to click into the "Installed Version" column and open a web browser. The "Application / link .." column at least is underlined and gives a hint, but clicking an empty cell raising the browser is unusual. Also it is the logical target to select a row (if one learned that that "Application / link .." pesters one with an unwanted browser) - it's the biggest column. And it does not link to a specific version, but to the same as the second column. Strange.  

- The browser is a secondary problem. Click is worst
- It would be better to have an additional "Go to home page" or the like button to raise the browser, instead to have it on the grid at all.  Better guidance for customer, not overloaded grid, no surprising action **while on simple like to select a row in a grid**.

**Comment by Jimrnelson** [comment]
The code that opened the application home page when clicking on the "Installed Version" has been removed.
