### ISSUE TITLE
Running Vanilla Thor raises browser

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#215]
## 📝 Provide detailed reproduction steps (if any)
1. Run CFU
2. Click "Application / link .." or "Installed Version"

### ✔️ Expected result

Thor installs

### ❌ Actual result

A browser window opens on top of my screen

### Remarks
There might be valuable information, but either one ask customer to open it, or allow to raise from the CFU dialogue. In all cases open a browser without consulting customer is bad and dangerous behaviour one expect by the bad guys. Rings any alert.

**Comment by Jimrnelson** [comment]
This appears to be the same as #214, which has been addressed.
