### ISSUE TITLE
Closing CFU with ALT+F4

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#216]
## 📝 Provide detailed reproduction steps (if any)

1. Run CFU
2. Press Alt+F4

### ✔️ Expected result

None or closing VFP

### ❌ Actual result

1. Closes CFU
2. Raises "Thor Configuration"
3. VFP still open

**Comment by Jimrnelson** [comment]
Check For Updates is a modal form, so pressing Alt+F4 has no effect.
