### ISSUE TITLE
Canceling Thor Configuration

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#217]
## 📝 Provide a description of the new feature

There is no way to cancel out of "Thor configuration" without storing the changes. Possibly one changes something and the dislike this? Some stuff is scatterd and on might not remeber old value

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
> There is no way to cancel out of "Thor configuration" without storing the changes. Possibly one changes something and the dislike this? Some stuff is scatterd and on might not remeber old value

Unfortunately, that is correct.  The Thor Configuration form updates many different tables and the changes take effect immediately, as you identified.
