### ISSUE TITLE
Check for Upates / CFU

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#218]
## 📝 Provide a description of the new feature
On the the check for updates via `RunThor.prg`, a way to turn CFU of would be nice. Thor could be enough. (via parameter, so customer can decide)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
See the documentation for  [RunThor.PRG](https://github.com/VFPX/Thor/blob/master/Docs/Thor_running.md), which states, in part:

> The parameter tnDays is the interval in days between calls to ‘Check for Updates’. A value of 1 means that it will be performed in your first IDE session of each day; a value of 7 means once a week. If the parameter is missing or is not a positive number, ‘Check For Updates’ is not called.

**Comment by lscheffler** [comment]
@Jimrnelson  Nobody doubts this. This is issue is called a **Feature Request**

The request was *Allow an option to **only Update Thor**, do not run CFU*

I can not see why, quoting an obvious part of  the docu, this feature request is closed?

**Comment by Jimrnelson** [comment]
Hey, this was a simple misunderstanding of your request.  Don't get all bent out of shape.

CFU is a single process for getting updates of VFPX projects, including Thor and many many others.

Your request was, when using RunThor:

>  a way to turn CFU off would be nice

That was what I responded to, a way to use RunThor to turn off CFU, which meant all updates.

I understand now that this was not your intent.

I suggest leaving this issue closed and restating your request as a new issue.

**Comment by lscheffler** [comment]
It was not intended, but I share this feeling if canceled. We should either add more smileys or do more laughs to ourselfs.
And sometimes patiently ask and answer. We both are triggered to fast.
:)

**Comment by lscheffler** [comment]
This describes it very well.
