### ISSUE TITLE
Update cycling

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#22]
The update of Thor itself starts on every start of VFP, or at least the first try to start _Check for updates_ on a VFP instance.
```

---------------------------
Allow CLEAR ALL, etc.?
---------------------------
Ready to install 1 update(s):

        Thor: Thor - 1.43 - December 28, 2021 - 20211228

CLEAR ALL and CLOSE ALL statements must be run in order to update.

Do you wish to continue?
---------------------------
Ja   Nein   
---------------------------

```

**Comment by lscheffler** [comment]
Yes. I would be annoyed otherwise too, but you wrote that you alter the updater. Let me know if If can check something / trace something.

**Comment by lscheffler** [comment]
Ok,  A bit more of the flow

- I start _Thor / Check for Updates_
- Thor runs the Messagebox as above
- Thor comes up with a _Complete_ MsgBox and something about the froum to discuss something
-  Raises the _Update status_ form
- I close and reopen VFP(A)
- I get MsgBox
```
---------------------------
Installation complete
---------------------------
Thor - 1.43 - December 28, 2021 installed
---------------------------
OK   
---------------------------
```
followed by the one _Clear All / Close All_ as above.
- _Yes_
  -  Error. 
     - Message() `File access is denied [...]thor.app`
     - Message(1) `erase (addbs(_screen.cThorAppFolder) + 'Thor.app')`
   - if I return out of the error I see the _Update status_ form
   - after closing, _Thor configuration_ form
If I close / open again, I t does not raise the flow, but as soon as I check for updates..

Sometimes I do not get the error, I have no idea under what circumstances.

The app is dated Jan th 6 2022, on this day I remember to have tried an update.   
I. as the user running VFP, can delete the file on the explorer. If VFP is closed. It looks a bit like VFP itself is sitting on _thor.app_

**Comment by DougHennig** [comment]
Choose Configure from the Thor menu and check the version and date at the bottom of the form; is it 1.43 dated December 29, 2021?

**Comment by lscheffler** [comment]
No, it's 1.43 December 28, 2021

**Comment by DougHennig** [comment]
What does Thor\ThorVersion.txt (the same folder containing Thor.app) contain? It should be "Thor - 1.43 - December 28, 2021- 20211228". If it isn't, change it to that and that should stop the update cycling.

**Comment by rschummer** [comment]
I updated this morning. Update went fine, the Configuration and Launcher dialogs show the correct version and date. I wanted to run the Check for Updates to see the dialog since I noticed it was part of the forms that were updated. When I run Check for Updates I am getting prompted to install the version I just installed:

---------------------------
Allow CLEAR ALL, etc.?
---------------------------
Ready to install 1 update(s):

        Thor: Thor - 1.43 - December 28, 2021 - 20211228

CLEAR ALL and CLOSE ALL statements must be run in order to update.

Do you wish to continue?
---------------------------
Yes   No   
---------------------------

**Comment by lscheffler** [comment]
ACK,
_ThorVersion.TXT_ is `Thor - 1.43 - December 28, 2021- 20211228`

**Comment by DougHennig** [comment]
This is fixed: there was an extra space in the version number which made it look like a different version was available.

**Comment by lscheffler** [comment]
Test finished, runs as expected.
