### ISSUE TITLE
GoFish in Thor Base

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#221]
# Issue
There should be no GoFish relevant stuff in Thor, since GoFish is an independent product.

## 📝 Provide detailed reproduction steps (if any)

1. Get vanilla Thor
2. install "mandatory" modules
3. Search for GoFish

### ✔️ Expected result

No file \*GoFish\*.\*, except in Updates directory

### ❌ Actual result
Found files
```
Thor/Tools/Images/GoFish16.bmp
Thor/Tools/Procs/GoFish.h
Thor/Tools/Procs/Thor_Proc_GoFishSearchEngine.vc2
Thor/Tools/Procs/Thor_Proc_GoFishSearchEngine.vct
Thor/Tools/Procs/Thor_Proc_GoFishSearchEngine.vcx
Thor/Tools/Procs/Thor_Proc_UnInstallGoFish5.prg
Thor/Tools/Thor_Tool_GoFish_SetOptionsToDefault.prg
Thor/Tools/Thor_Tool_Repository_GoToGoFish4.PRG
```
and fxp

**Comment by Jimrnelson** [comment]
Consolidated into #243
