### ISSUE TITLE
Scattered URLs

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#225]
The URLs to reach Thor and ThorRepository are scattered over may files. This is bad for maintaining, testing and forking. Also the provider of this service is not be know to keep things alive to eternity.

It might be a better idea to have the base URLs in a header file that is used where needed.

This is not true for the documentation, but this is a different problem.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Consolidated into #243
