### ISSUE TITLE
Documentation / install instructions, several problems

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#226]
The file Docs/Thor_install.md states:

> Extract the Thor-master\Installed Files subdirectory from the ZIP file to the installation folder of your choice (see details below on how to [choose an installation folder](https://github.com/VFPX/Thor/blob/master/Docs/Thor_install.md#choosing-an-installation-folder) ). After this step your installation folder should only contain the Source folder and Thor.APP.

The *Installed Files subdirectory* in the zip contains *Source* directory and *Thor.APP* file **and *Thor* directory**.

----
The file links to download https://github.com/VFPX/Thor/archive/master.zip and extract files from some subdirectory. This is overcomplicated and error prone. A lot of people end up with *Thor/Installed Files* or *Thor/Thor-master/Installed Files*   
A link to [Thor.zip]( https://github.com/VFPX/Thor/raw/master/ThorUpdater/Thor.zip) (https://github.com/VFPX/Thor/raw/master/ThorUpdater/Thor.zip) should do. *Installed Files* is the content of Thor.zip?

**Comment by lscheffler** [comment]
It looks like the **Thor directory** mentioned above is the important part. The **Source** is compiled into the App, there is no need to put this on the install folder.

If one expand ThorUpdater/Thor.zip without the Source directory, it looks likes it runs without a problem. The `Thor.h` and the related are missing if one must compile some of the prgs (by implementing #225).   
Either
- one tells the ps1 script only to include the files one need
- does not code in "Installed Files", but use something like VFPXDeployment to move the files needed to Installed Files" directory
- moves the header files

**Comment by Jimrnelson** [comment]
Suggested changes have been made to the installation document for Thor (as well as a few other minor edits).
