### ISSUE TITLE
contributing.md

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#229]
The steps  7 and 8 might be better switched. The Foxbin2Prg can not catch files changed by the compile. The state of the folder should match the version populated.

It might have little influence here, but it is better to have one single work flow over many projects.

**Comment by Jimrnelson** [comment]
Compiling a binary file will cause changes in the text file?  I would never have guessed this -- I thought the text file was the canonical representation, from which the binary file could always be re-created.

Can you indicate what might change in the text file as a result of compiling the binary?

**Comment by lscheffler** [comment]
It's a more general advice. The most basic file touched is the PJX itself.
- version number of the PJX could be incremented
- a project hook can catch in

It is not happening here, but for my working code, for example, I set a debug-switch somewhere, the beforebuild projecthook reads this and starts to alter the pjx, for example including files. Just a wizzzard. So for simplicity I compile first, and transform and commit later.   
Or think it the other way around: transform + commit is a unit as stage + commit. I do it, if possible, in on step. (And I have code doing this. Transform the whole active pjx / or all pjx in the IDE + stage + commit. Speed optimized.)   
My work flow for Thor is
1. ...
2. compile
3. create the zip  stuff etc
4. transform
5. stage
6. commit

Where, in my mind, 4.-6. is just a unit. Like "the stuff I need to do to create the commit".

---
For me, the text file is not the canonical representation. I read it as an additional state (if you like the state idea of git as in https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F; The Three States):
- Working Directory
  - Binary
  - Text version
- git
  - Index (aka Stage)
  - Repository

If the binary is changed, the binary is right. If I gather from the repo, the text file is right.   
In the same way you can not say that Working Directory, Index or Repository is cannonical. It changes.

I code on binary level. I dislike prg based classes, it's so much more convenient to have multiple methods and the Property window visible.   
But if I start to look up changes, merge, I switch to the git view - the text level, because of it's simplicity.

Both views have positives.

**Comment by Jimrnelson** [comment]
Fixed in Thor 1.46.17 - Released 2023-12-16
