### ISSUE TITLE
Running links from Update form on VFPA

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#23]
FYI
If I try to open the links from VFPA I get an error message   
`File 'c:\program files (x86)\vfpa\ffc\_environ.vcx' does not exist.`

**Comment by DougHennig** [comment]
I am also using VFPA and do not have this error. Thor requires that the VFP HOME() folder has a subdirectory called FFC and that subdirectory contains (among other things) _Environ.vcx.

**Comment by lscheffler** [comment]
I need to check this. And why it is not where it belongs.

**Comment by lscheffler** [comment]
The  _FFC_ was named _FFC\__, why ever. Thor seems to be the only one using this here. :)
