### ISSUE TITLE
icon not found

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#235]
## 📝 Provide detailed reproduction steps (if any)

1. Clone Thor
2. MODIFY FORM "Installed Files\Thor\Tools\Procs\checkforupdates.scx"

### ✔️ Expected result

Should open

### ❌ Actual result

Complains about missing *Thor.ico*

## Comment
Icon file is on several places, but not on the one where the scx expects it.

**Comment by Jimrnelson** [comment]
Fixed in Thor 1.46.17 - Released 2023-12-16
