### ISSUE TITLE
Files in soure directories / tidy

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#237]
Source in the sense of Thor - source, not the "Source" directory.

Some of those files are named in a different issue, listed here for completeness

There are some files that looks doubled between "Installed Files\Thor\Tools\" and "Installed Files\Source\", out of time or not placed in the right directory. 
| tools | source | reason for oddness |
|--|--|--|
| THOR_TOOL_THORINTERNALFRAMEWORK.PRG | thor_tool_thorinternalframework.prg | codeplex, outdated |
| thor_tool_thorinternalframeworkhelp.prg | thor_tool_thorinternalframeworkhelp.prg | codeplex, outdated |
| thor_tool_thorinternalhelp.prg | thor_tool_thorinternalhelp.prg | codeplex, outdated |
| thor_tool_thorinternalrepositoryhomepage.prg | thor_tool_thorinternalrepositoryhomepage.prg | codeplex, outdated |
| thor_tool_thorinternaltweets.prg | thor_tool_thorinternaltweets.prg | codeplex, outdated |
| thor_tool_thor_checkforupdates.prg      | thor_tool_thor_checkforupdates.prg      | double |
| thor_tool_thor_community.prg            | thor_tool_thor_community.prg            | double |
| thor_tool_thorinternalalltools.prg      | thor_tool_thorinternalalltools.prg      | double |
| thor_tool_thorinternaledit.prg          | thor_tool_thorinternaledit.prg          | double |
| thor_tool_thorinternalmanageplugins.prg | thor_tool_thorinternalmanageplugins.prg | double |
| thor_tool_thorinternalmodifytool.prg    | thor_tool_thorinternalmodifytool.prg    | double |
| thor_tool_thorinternalrepository.prg    | thor_tool_thorinternalrepository.prg    | double |
| thor_tool_thorinternalruntool.prg       | thor_tool_thorinternalruntool.prg       | double |
| thor_tool_thorinternalthornews.prg      | thor_tool_thorinternalthornews.prg      | double |
| thor_tool_thorinternaltoollink.prg      | thor_tool_thorinternaltoollink.prg      | double |
| thor_tool_thorinternalusagesummary.prg  | thor_tool_thorinternalusagesummary.prg  | double |
| n/a | tables/thor_tool_togglecommentcolors.prg | naming means to be found in tools? |
| n/a | t1.prg | failed naming convention or test |
| n/a | try1.prg | looks like some test |

different folders
| file | problem |
|--|--|
| updaters\updates\old_thor_update_thor_repository.prg | even named "old" |
| thor_update_thor_repository_beta.prg | outdated URL |

The superfluous files should be eliminated from the repository.

**Comment by Jimrnelson** [comment]
Consolidated into #243
