### ISSUE TITLE
Thor does not update FoxBin2Prg

### ISSUE THREAD

**Issue by AnatolBazyukin** [VFPX/Thor#238]
After checking for updates we get the following result:

![foxBin2PRG](https://github.com/VFPX/Thor/assets/33526380/31d46af5-0b2a-4a64-b1a1-77cf1dc56127)

We perform the update and receive the following message:

![message](https://github.com/VFPX/Thor/assets/33526380/234c20ca-f96f-455c-9dc6-fb29e548cde3)

The file is not loading.

**Comment by lscheffler** [comment]
@DougHennig Issue could be closed
