### ISSUE TITLE
Problem with CFU and two instances

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#239]
## 📝 Provide detailed reproduction steps (if any)
It's a bit hard to reproduce and to deliver debug info. I was in a different problem so it could be (3) or (4). So, out of my mind:

1. Run CFU in VFP instance A,
2. Update a module (here VFPXDeployment)
3. Open a new VFP instance B using `RunThor.prg` 
4. Run VFPXDeployment

### ✔️ Expected result

Run

### ❌ Actual result

It fails while trying to recompile a prg, because the fxp is blocked by instance A.

## 📷 Debugging Info
See above. If I run into this again, I will give more information.

**Comment by lscheffler** [comment]
It's not that simple, I fear.

Possibly I was not clear. On Instance A, CFU is finished, and the instance should not be running any Thor stuff except the menu. Only it keeps the fxp open / in memory.   
I guess that CFU should clear itself after run.

And looking from an other point: What is open, and why does a different instance decide to compile the prg at all.

**Comment by Jimrnelson** [comment]
CFU deletes all FXPs in Tools and Tools\Procs folders, forcing them to be recompiled when next used.

I have no idea which FXPs are still in use after CFU, nor how to clear them.

**Comment by lscheffler** [comment]
That's why I think you should keep it open for a while. I had it closed to fast by accident, so I could not look closer / provide better information, but I will do similar stuff the next days. There is a chance I run into it and might provide better detail.

If I can not reproduce, we can close all the time.
