### ISSUE TITLE
Class definition frmScopeFinder is not found

### ISSUE THREAD

**Issue by mattw919** [VFPX/Thor#24]
New Windows 10 installation
Brand new installation of VFP 9 SP2
Downloaded and installed Thor
Installed Thor tools - including the vfp-git-utils and FoxBin2Prg
When running the Prepare for Git-Hg Commit, I immediately get the error "Class definition frmScopeFinder is not found".
Debugging the error shows a temporary prg, failing on the bolded line inside of Case lnPCount = 2, starting with  loObject = 

```
Otherwise
		lcClass	   = Getwordnum (lcClassName, 1)
		lcClassLib = Getwordnum (lcClassName, Getwordcount (lcClassName))
		lcFileName = Execscript (_Screen.cThorDispatcher, 'Full Path=' + lcClassLib)
		Do Case
			Case lnPCount < 2
				loObject   = Newobject (lcClass, lcFileName)
			Case lnPCount = 2
				**loObject   = Newobject (lcClass, lcFileName, '', lxP1)**
```

  
  lcClass value is: "frmScopeFinder"
  lcFileName is: ""
  lxP1 is: "Prepare for Git-Hg commit"

**Comment by DougHennig** [comment]
That sounds like a Git Utilities rather than a Thor issue: https://github.com/mikepotjer/vfp-git-utils

**Comment by mattw919** [comment]
The more I looked into it, I think you're right. I thought it was a Thor launcher issue, but maybe not.

**Comment by mattw919** [comment]
@DougHennig

**Comment by mattw919** [comment]
@DougHennig I'm back to thinking it's a Thor installation issue. I just updated a second PC to the latest version of Thor and the behavior is the same. With Mike Potjer's help, he pointed out that the issue is Thor couldn't find the file Thor\Tools\Procs\Thor_Proc_ScopeProcessor.vcx .  It looks like most other files are there (39 files in that folder), but none that are named Thor_Proc_ScopeProcessor.  I've tried reinstalling on both machines several times, no luck.

**Comment by DougHennig** [comment]
I added the Thor_Proc_ScopeProcessor files to the Thor\Source\Procs_For_Thor folder, where I believe the files in  Thor\Tools\Procs are copied from.

**Comment by mattw919** [comment]
Ok, I downloaded again and reinstalled.  If I look in C:\<thor install folder>\Thor\Tools\ThorRepository-master\Source\Procs  There are 106 files.  Looking in C:\<thor install folder>\Thor\Tools\Procs , there are 40 files.  I still don't see the Thor_Proc_ScopeProcessor files in there, but they are in the ThorRepository-master subfolder. 

Should I copy them (or all files) from .\Thor\Tools\\ThorRepository-master\Source\Procs  to  .\Thor\Tools\Procs ?

**Comment by DougHennig** [comment]
I don't know the internals of Thor well enough to know how those files get into Thor\Tools\Procs so just copy Thor_Proc_ScopeProcessor.* into that folder.

**Comment by mattw919** [comment]
Got a little farther by doing that. It did prompt for the scope, but errored later in Thor_Proc_GitUtilities. 
![image](https://user-images.githubusercontent.com/58303790/153656253-0aaa888e-1d5b-49c8-a383-49e3b654c272.png)
I ended up copying all of the files and it did work with a minimal error, that I was able to fix.
Thanks for your help.
