### ISSUE TITLE
Issue restarting after CFU

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#241]
## 📝 Provide detailed reproduction steps (if any)

Still like #239. Thor / CFU is not cleaning up

1. Run and complete CFU toward Thor 1.46.17
2. Open other instance of VFP

### ✔️ Expected result

Instance should open

### ❌ Actual result

Error

## 📷 Debugging Info
![grafik](https://github.com/VFPX/Thor/assets/27769909/b31b1a86-8e55-4d23-9c1c-cc6ef2bb89a3)

[memo dump](https://github.com/VFPX/Thor/files/13692986/memo.txt)

## Additional info
If one closes ALL VFP and reopen, one get a messagebox that Thor 1.46.17 is installed, and all runs again

**Comment by lscheffler** [comment]
### Additional stuff
I run CFU more then once today, I do some tests on VFPXDeployment via *My Updates*. I changed nothing to the Thor directories.

Now I receive again:
![grafik](https://github.com/VFPX/Thor/assets/27769909/667d3a75-db12-4979-abf0-df5e534f50ec)

This time it was no problem to open a new instance of VFP

**Comment by Jimrnelson** [comment]
Thor 1.47 - Released 2024-01-04
