### ISSUE TITLE
Thor Tools menu indicates if Intellisense By Dot is active.

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/Thor#242]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

Self-descriptive -- if "IntellisenseX by Dot" is active, there should be a checkmark for it in the Thor Tools menu.

Note:  I have no recollection of this ever being discussed when implementing Thor.  It may be a little tricky since all the Thor menus are generated "on the fly".

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Thor 1.47 - Released 2024-01-04

**Comment by lscheffler** [comment]
Works like a charm
