### ISSUE TITLE
Issue updating

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#245]
## 📝 Provide detailed reproduction steps (if any)

1. Run VFP with Thor, do nothing
2. Run second instance of VFP with Thor (the projects will not load)
3. Start  CFU

### ✔️ Expected result

Update

## 📷 Debugging Info
Please add screenshots of
- Error Message   
   ![grafik](https://github.com/VFPX/Thor/assets/27769909/83cdd9d9-4e65-482e-9d9a-3712b73fbfe8)

- Windows from the debugger   
Did not run into debugger. 

It simply looks like Thor is still in memory on the first instance.

How to fix this file for common user? (I know how to help myself)

**Comment by lscheffler** [comment]
Additional problem, I think it's related, so no new issue.

- Start additional VFP instance, starting Thor

Error message (error 17505 in Line 401):
![grafik](https://github.com/VFPX/Thor/assets/27769909/d7fca8b5-7502-433a-a85a-098d170b26fe)

Sorry; I got error the message through my handler, so no trace visible, thanks to EXECSCRIPT.    
![grafik](https://github.com/VFPX/Thor/assets/27769909/4b7ca43e-339e-4b01-97fc-c9ecbed778c1)

**Comment by lscheffler** [comment]
After closing all VFP and rerun, I got a message that Thor is installed, after that adding subsequent instanced worked.

**Comment by lscheffler** [comment]
Running CFU again (to test #224)   
![grafik](https://github.com/VFPX/Thor/assets/27769909/0a07a889-a9f5-4d14-8637-20cb303782b9)    
What? I have done this! 

Second instance is open, same failure as in OM ...

**Comment by Jimrnelson** [comment]
> 1. Run VFP with Thor, do nothing

Does this mean you ran VFP with the new version of Thor or an older version?

The problem in older versions (those before 1.47) is that they left an object open that had all the Thor tables in use.

I believe that this problem is solved if you are running 1.47

All subsequent issues you report here are a result of incomplete installations.

**Comment by lscheffler** [comment]
@Jim, I have not touched the folder other then through CFU

Step by step
- Thor 1.46 was installed
- saw the mails from github
- started VFP, running Thor on installed my comp, this is 1.46
- started second instance, running Thor on installed my comp, this is 1.46
  - this is VFP on the same setting structure, with the same foxuser
- started CFU on second instance
- Error on the instance with CFU running

---
I closed the debugger from #246 and run Thor/Options subsequent, without Clear All. Same error
![grafik](https://github.com/VFPX/Thor/assets/27769909/08e45ef7-f16c-47ee-bcba-868ff47eb9b9)

I checked the Datasessions, the table is not open, this is the one and only VFP instance. Only the path is nonsense, it's *E:\SE\thor\thor\Thor\Tables*, nit *E:\SE\thor\thor\Tables*, see
![grafik](https://github.com/VFPX/Thor/assets/27769909/a3c9c126-9186-49df-a416-480118e877b9)

**Comment by Jimrnelson** [comment]
Understood.

This problem will occur as long as you are using any version before today's (1.47).  

That is the version that has the (hoped for) fix.

Of course, there is no way to fix an earlier version.

The problem with the file in use had to to with a different datasession than the default.

***

When you state a "newly started Thor", the same applies -- until you are running/using 1.47, you'll get this error.

**Comment by lscheffler** [comment]
I think it was clear that all happened after I started CFU to update to 1.47    
The whole idea running CFU and the like is testing the changes of 1.47

---
> The problem with the file in use had to to with a different datasession than the default.

As I wrote above. There was **no** other datasession, **no** cursor open, **and only this** instance of VFP active. **But** the path is wrong.

**Comment by Jimrnelson** [comment]
> I think it was clear that all happened after I started CFU to update to 1.47
> The whole idea running CFU and the like is testing the changes of 1.47

There's the catch-22!  

My changes will work when you start in 1.47 and move it to some future (not-yet-created) release.  

There is no way for you to test whether they work when moving from some earlier release to 1.47.

***

> There was no other datasession, no cursor open, and only this instance of VFP active. But the path is wrong.

The error you got was an access error, meaning the file existed but could not be exclusively opened.  That is because it was still open in the other session, in a different datasession.

**Comment by lscheffler** [comment]
> > I think it was clear that all happened after I started CFU to update to 1.47
> > The whole idea running CFU and the like is testing the changes of 1.47
> 
> There's the catch-22!
> 
> My changes will work when you start in 1.47 and move it to some future (not-yet-created) release.
> 
> There is no way for you to test whether they work when moving from some earlier release to 1.47.

Not all of it. Some i can test - and none should raise this error. :)
 
> > There was no other datasession, no cursor open, and only this instance of VFP active. But the path is wrong.
> 
> The error you got was an access error, meaning the file existed but could not be exclusively opened. That is because it was still open in the other session, in a different datasession.


What do you not understand fr0m **NO CURSOR WAS OPEN ANYWHERE**?? A table is a cursor, that is stored permanently? The files was blocked from whatever, but not from something dealing with VFP TABLES OR CURSORS on the level of VFP data engine.

Sorry for the hickup on the path, to many "Thor" in the path. And me locking for to long into the monitor for today. CU tomorrow.

**Comment by Jimrnelson** [comment]
@lscheffler 

You had two VFP sessions.  The first VFP session you started using version 1.46.  That VFP session left an object around which had a private datasession where all the Thor tables were open. (This does not occur is you start in 1.47)

In the second VFP session, you got an error where the update was trying to get exclusive access to a Thor table.  It generated an access error for that table because it was trying to access a table left open in the private datasession in the other VFP session.

**Comment by Jimrnelson** [comment]
@lscheffler 

Earlier in this thread, you described your steps as follows:



> Step by step
> 
> * Thor 1.46 was installed
> * saw the mails from github
> * started VFP, running Thor on installed my comp, this is 1.46
> * started second instance, running Thor on installed my comp, this is 1.46
>   
>   * this is VFP on the same setting structure, with the same foxuser
> * started CFU on second instance
> * Error on the instance with CFU running

I understand that this occurs when you start your sessions with V1.46.X 

There is nothing I can do about that, I do not support that version any more.

If the error occurs when you start your sessions with the latest version, 1.47, that will be worth reporting.

**Comment by lscheffler** [comment]
> @lscheffler
> 
> Earlier in this thread, you described your steps as follows:
> 
> > Step by step
> > 
> > * Thor 1.46 was installed
> > * saw the mails from github
> > * started VFP, running Thor on installed my comp, this is 1.46
> > * started second instance, running Thor on installed my comp, this is 1.46
> >   
> >   * this is VFP on the same setting structure, with the same foxuser
> > * started CFU on second instance
> > * Error on the instance with CFU running
> 
> I understand that this occurs when you start your sessions with V1.46.X
> 
> There is nothing I can do about that, I do not support that version any more.
> 
> If the error occurs when you start your sessions with the latest version, 1.47, that will be worth reporting.

It fails updating, but you don't care. You might read it as you like. If one clarifies something, you insist on older statements.

The CFU was opened while 4.17 installed, I closed the whole VFP, but this whole process is not stable. The install of 1.47 started before 4.1.2024 19:58, this is the timestamp of the OM of this issue. **ANYTHING** after that is 1.47 whatever the installer assumes or retries. The failure happens while updating to 1.47, so the update must manage this problem. What do you think I'm reporting?

ok, from scratch

**Comment by lscheffler** [comment]
Runs with 1.47.01 Great.
