### ISSUE TITLE
error starting configure

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#247]
Basically the same as https://github.com/VFPX/Thor/issues/245#issuecomment-1877730920. по-моему, one should not deal with this outside of #245 , but since it is rejected to be handled, I try atomic. It seems not clear enough there, so I try to show the problem better.
## 📝 Provide detailed reproduction steps

1. run CFU to install 1.47
2. close vfp
3. open vfp
4. start *Configure*

### ✔️ Expected result

Configuration  window should open

### ❌ Actual result

Failure, Thor tries to locate a table on the wrong place
![grafik](https://github.com/VFPX/Thor/assets/27769909/bf12cd9d-82be-4924-8b53-1fe266c7aee1)

![grafik](https://github.com/VFPX/Thor/assets/27769909/9dc0bba9-4065-488a-b6d1-2232f5fc2a09)

Note the value of `lcfolder` and `tctablename` and the line in the trace window.

| var | value |
| -- | -- |
| lcfolder | `"E:\SE\THOR\THOR\Tables\"` |
| tctablename | `"MenuDefinitions"` |
| Line 10 (`(lcFolder + tcTableName)`) | `"E:\SE\THOR\THOR\Tables\MenuDefinitions"` |

This is a screen shot of the directory structure of this folder `"E:\SE\THOR\THOR\"`, as a might see, there is no subdirectory `"Tables"` in this directory. If one looks on the left, there is a tree with the whole subdirectories of `"E:\SE\THOR\THOR\"`, one can see that `"Tables"` is in subdirectory `"Thor"`, making a total path `"E:\SE\THOR\THOR\THOR\Tables"`. 
![grafik](https://github.com/VFPX/Thor/assets/27769909/e9991cb6-0a86-4700-a119-e5ce161f6d14)

I hope now this is clear enough.

**Comment by Jimrnelson** [comment]
This issue corrected in Thor 1.47.01 - Released 2024-01-05

Thanks for the error report.
