### ISSUE TITLE
Position of the Clear All Message

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#249]
## 📝 Provide a description of the new feature

The "Clear ALL" Messagebox like form is centred on main screen. 
![grafik](https://github.com/VFPX/Thor/assets/27769909/5fe3ea64-fa19-4756-b012-fbf956035aae)

Would it be possible to center the form on _SCREEN, _VFP, or simple on the monitor with VFP? Since the bit unwanted ThorNews opens on my main monitor *and gets focus* the form is hidden ...

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
This issue will be fixed in the next update.

Not exactly in the way requested, though, as the ThorNews will simply not appear any more and thus it will not obscure this CLEAR ALL form.

**Comment by lscheffler** [comment]
I have 4 monitors, **main** is not in my focus. It's a pain.

**Comment by Jimrnelson** [comment]
That form is created by `Thor_Proc_MessageBox.prg` (in the Procs folder).

Feel free to supply a modified version that does what you want, as long as it does not alter the current behavior of centering the form in the main VFP screen.  (That is, it should not restore the last position, but always center.)

**Comment by Jimrnelson** [comment]
Yes, some imprecision in terminology,

It sets

`   Thisform.AutoCenter = .T.`

**Comment by lscheffler** [comment]
And this depends on `ShowWindow`. 2 will center to main screen aka as top level. I do not see why we need `ShowWindow=2`here.

**Comment by Jimrnelson** [comment]
I don't understand your reference to `ShowWindow = 2`.  

The relevant code is where AutoCenter is set to .T.  

If you are going to make any changes to this so that it works for you, it should still work the original way for others.

BTW, please try to minimize the changes the make.

**Comment by lscheffler** [comment]
AutoCenter centers relative to the parent form. This is either
- ShowWindow = 0 -> "In screen" _SCREEN
- ShowWindow = 1 -> "In top level" An other VFP top level form
- ShowWindow = 2 -> "As top level" main screen of the computer

This form uses 2, so it opens centred on the main computer screen.

----
There is no way to have both, ShowWindow = 2, or guaranteed centred on _SCREEN. So

> If you are going to make any changes to this so that it works for you, it should still work the original way for others.

is impossible to achieve. 

The idea you need to think about is, where do you **think* it should appear. Then change accordingly. *Me I would simply set ShowWindow = 0, so it's centered on _SCREEN like any other normal messagebox. Possibly 1, if one is working with top level, something I do only rarely.*

---
I will not touch this code, I have no idea who and why else uses this pseudo-messagebox.   
The programmer of this tool had no idea of multiple monitors, and that somebody will not run VFP on the main one. Or she would have noticed.

Aside of this, it's bad to have the messageboxes mixed. Some this and some standard is odd.

**Comment by Jimrnelson** [comment]
> This form uses 2, so it opens centred on the main computer screen.

Actually, that is not correct, as there is no place in the form where ShowWindow is set to 2, so that's not it.  (That wouldn't work with a modal form anyway, as far as I understand it.)

Is there a setting for ShowWindow that would work better for you?

**Comment by lscheffler** [comment]
**I** think *1*, this is, as far as I understand help, centred to the (active?) top level form, or if there is no top level form, centred to _SCREEN. This should cover all. The form is centred where one is looking to.

**Comment by Jimrnelson** [comment]
Corrected in Thor 1.47.02 - Released 2024-01-13 #253

**Comment by lscheffler** [comment]
Now at least it's on top. It's still on the wrong monitor.

**Comment by Jimrnelson** [comment]
It's using VFP's MessageBox.

I have no control over where that goes.
