### ISSUE TITLE
Thor Repository doesn't install correctly

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/Thor#25]
Installing Thor on a new machine, _Check For Updates_ does not install the Thor Repository files in the correct location. It appears that the repository files ought to be installed in the `Tools` folder, but instead they are extracted into a `ThorRepository-master\Source` subfolder.

![image](https://user-images.githubusercontent.com/9847353/157750071-86175edc-0eb7-44fa-a359-f35a37dc9a22.png)

The result is that various Thor Repository features are not available, such as dynamic forms.

![image](https://user-images.githubusercontent.com/9847353/157750880-532687ee-7e39-4f39-9dd6-0c86af021f19.png)

Moving all the files from `ThorRepository-master\Source` to the `Tools` folder fixed the problem.

**Comment by DougHennig** [comment]
Fixed.
