### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#250]
A problem to play kids like me, anyway, it should not happen.  I was testing for #227 (what works, thanks)
## 📝 Provide detailed reproduction steps (if any)

1. Copy plain Thor installer of 1.47 into a folder
2. Run VFP, sttartin Thor.app
3. OK unit until CFU form
4. Do not change
5. End the form

### ✔️ Expected result

Proceed with VFP

### ❌ Actual result

Error 1, line 10
File 'e:\se\tmp\thor\tables\menudefinitions.dbf' does not exist.

**Note** For this example *e:\se\tmp\thor* is the path of the Thor.App

![grafik](https://github.com/VFPX/Thor/assets/27769909/1ff88aec-d0c5-4706-9592-d6268127eb98)

After closing VFP and rerun via Thor.app, it repeats into eternity. If one run the subsequent try with RunThor.prg, it sucseeds.

The update of the "normal"  installation of Thor (a Thor already installed ) was running fine, but then this was running on RunThor.prg. I beg your pardon, I was to fast removing the backup, so I can not try with Thor.app

It looks like a problem with 1.47 (at least it does not happen if one uses vanilla 1.47.1, but there is no update). So far, this not of general interest, this is just me.   
What is bad is, that it runs 1.47 code in this moment at all. I know this is because I started the App, and anything running comes out of the app - iow of the old version. There is no simple way out - except using a wrapper prg or app in general.

**Comment by Jimrnelson** [comment]
@lscheffler 

You are correct, this is a bug in 1.47 that has been fixed in 1.47.01.  There is no way out except to update to 1.47.01

**Comment by lscheffler** [comment]
Only it is a problem that highlights an other on - or is an update *from* 1.47.01 not run in 1.47.01 context after the Thor data is downloaded? This must be solved. It will not raise *this* special problem, but is a good way to create new ones.
