### ISSUE TITLE
Sorting of CFU

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#251]
## 📝 Provide a description of the new feature

If one set installed modules to *Never update* (I used for #246 to not wait to much) the stuff get's ordered odd. 

![grafik](https://github.com/VFPX/Thor/assets/27769909/0b1d58ba-b251-45ca-b2c3-52348b976c75)

Would it be possible to keep the stuff installed on top of the *Never updates*?

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Corrected in Thor 1.47.02 - Released 2024-01-13 #253
