### ISSUE TITLE
GoFish not included in Check For Updates

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/Thor#26]
GoFish 5 is not an available option in the Check For Updates dialog.

![image](https://user-images.githubusercontent.com/9847353/157752099-90202d07-c332-43a5-8050-a08d2b861696.png)

This is because the `Thor_Update_GoFish5.prg` file does not contain a valid URL for the version file. If you try to navigate to that URL in the browser, a page not found (404) error occurs.

![image](https://user-images.githubusercontent.com/9847353/157752300-f0a02bc7-fb0f-495e-9ebe-25336ce3f5ea.png)

**Comment by DougHennig** [comment]
Fixed.
