### ISSUE TITLE
Hot Keys for Thor Tools menu bars

### ISSUE THREAD

**Issue by billand88** [VFPX/Thor#265]
It kinda looks like you can mostly go straight down the list...

Take the first letter until you reach the "T's.

For some reason I have a "TB" which has "Pandora" as a sub menu, which doesn't run. 

Take the "T" in Tables, the "H" in Thor and if "TB" is real, take the "B". 

Then take the first letter to the end.

Yes, these have submenus that could use hot keys - but just these alone will help with discovery and navigation.

**Comment by Jimrnelson** [comment]
See my comment in #263
