### ISSUE TITLE
CodeAnalyst location error when Thor installs

### ISSUE THREAD

**Issue by WBStrider** [VFPX/Thor#266]
## 📝 Provide detailed reproduction steps (if any)

1. Select Update Thor
2. Select Code Analyst to be installed
3. Try to Run Cole Analyst
4. When prompted to select a File or Folder

### ✔️ Expected result

Ability to select a file

### ❌ Actual result

Cancel Suspend error due to Analyst.app not located where expected
D:\VFPThor\Thor\Tools\Apps\Code Analyst

D:\VFPThor\Thor\Tools\Apps\Code Analyst\CodeAnalyst-master contains a copy of the analyst.APP file,

After copying the analyst.app file to D:\VFPThor\Thor\Tools\Apps\Code Analyst\analyst.APP , the program works as expected.

Note: 1st issue created, ever.

**Comment by Jimrnelson** [comment]
@WBStrider 

Hey, glad to hear from you!

Sorry about the issue and glad that you found a relatively easy workaround.

And thanks for reporting the problem, I'll see what I can do to get it corrected.

**Comment by Jimrnelson** [comment]
@WBStrider 

This issue has been resolved.  Since you have already made modifications to get Code Analyst to work, there is nothing you need to do.
