### ISSUE TITLE
Finder neither installs correctly nor includes source code

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/Thor#27]
Finder is not installed correctly via Check For Updates.
1. It creates a custom subfolder named `Finder-master`, which is not correct.
2. The only content that is installed is documentation for Finder, not the tool itself.

![image](https://user-images.githubusercontent.com/9847353/157767280-93132744-56a5-449a-86f5-614fc2a77c44.png)

The main issue is that the [Finder GitHub repo](https://github.com/VFPX/Finder) does not include any source code, and `Thor_Update_Finder.prg` doesn't point to a valid Thor update file, like you have for [PEM Editor](https://github.com/VFPX/PEMEditor/tree/master/downloads/ThorUpdater), for example.

![image](https://user-images.githubusercontent.com/9847353/157767549-ba3e73d9-b696-40af-b3aa-46223ba430a4.png)

**Comment by DougHennig** [comment]
I can't find the source for Finder. You wouldn't happen to have a copy of it, would you?

**Comment by mikepotjer** [comment]
I used the old update code to install Finder from the old site, then zipped the source code Thor downloaded into my temp folder. Here you go.

[Finder.zip](https://github.com/VFPX/Thor/files/8233229/Finder.zip)

**Comment by DougHennig** [comment]
Thanks. I fixed the updater and it installs now, but I get an error running it. I'll look into it this weekend.

**Comment by DougHennig** [comment]
It installs correctly but it looks like it needs some work to run properly.
