### ISSUE TITLE
BeautifyX issuse

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#271]
BeautifyX issuse with below code

DECLARE INTEGER ShowWindow IN WIN32API INTEGER, INTEGER

above code changed as mentioned below when we click the BeautifyX

DECLARE INTEGER SHOWWINDOW IN WIN32API INTEGER, INTEGER

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

That's actually an issue with native Beautify, and not BeautifyX.

In depends on this setting:

![image](https://github.com/user-attachments/assets/b113b5b3-d6eb-4e31-96bb-6426d7059c85)
