### ISSUE TITLE
Finder App not found

### ISSUE THREAD

**Issue by Ajitweb** [VFPX/Thor#274]
Hi,
I am using VFP10
I installed Thor and then installed Finder and GoFish from the Thor Update Page.
Restarted VFP and the below picture is the Update Status

![FinderError01](https://github.com/user-attachments/assets/69e5de71-e6d1-4c9b-be97-4cb03f28fb18)

But I don't find Finder in the Tools Definitions Tab.

![FinderError02](https://github.com/user-attachments/assets/9657d321-c079-4158-bec7-e9cdd2a8d56c)

Is it a VFP10 compatibility issue?

Regards,

Ajit Abraham

**Comment by Jimrnelson** [comment]
@Ajitweb 

Thanks for finding this problem with installing Finder.

Please try installing it again (even if it says its already installed.)

**Comment by Ajitweb** [comment]
Thank you Jim. It is working perfectly.
Thanks for this awesome utility.
I have docked the Finder along with Command & Properties window. Wow !
I am also using Foxcodeplus for a great IntelliSense experience !
The only minor thing missing - is viewing the line numbers in the VFP Code editing window.

Regards,
Ajit Abraham
