### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#277]
## 📝 Provide detailed reproduction steps (if any)
Was poking around Thor (V 1.47.03) folders...
Tools folder, noticed an err file for Thor_Tool_PEME__OpenProject.prg
Line 61 Unrecognized command
Line is incomplete: _oPEMEditor.oUtils.
Is  this a  Thor bug or a 'Me' issue?

### ✔️ Expected result

No error

### ❌ Actual result

What is the actual result of the above steps?

## 📷 Debugging Info
See above

**Comment by Jimrnelson** [comment]
You can just delete or ignore that ERR file; it's meaningless.
