### ISSUE TITLE
IntellisenseX neither installs correctly nor includes source code

### ISSUE THREAD

**Issue by mikepotjer** [VFPX/Thor#28]
IntellisenseX is not installed correctly via Check For Updates.
1. It creates a custom subfolder named `IntelliSenseX-master`, which is not correct.
2. The only content that is installed is documentation for IntellisenseX, not the tool itself.

![image](https://user-images.githubusercontent.com/9847353/157769067-9fac6766-cedd-4d7e-9580-5613fa1684be.png)

The main issue is that the [IntellisenseX GitHub repo](https://github.com/VFPX/IntelliSenseX) does not include any source code, and `Thor_Update_IntellisenseX.prg` doesn't point to a valid Thor update file, like you have for [PEM Editor](https://github.com/VFPX/PEMEditor/tree/master/downloads/ThorUpdater), for example.

![image](https://user-images.githubusercontent.com/9847353/157769344-c6a4d38e-30c1-4ae7-a185-364c3bcb118b.png)

**Comment by mikepotjer** [comment]
Here is the IntellisenseX source code Thor downloaded into my temp folder using the update pointed at the old site.

[IntellisenseX.zip](https://github.com/VFPX/Thor/files/8233262/IntellisenseX.zip)

**Comment by DougHennig** [comment]
That one I found. Thanks, fixed now.
