### ISSUE TITLE
update windows doesn't show

### ISSUE THREAD

**Issue by alfacero** [VFPX/Thor#3]
Windows 10 64
vfp 9
after installarion of thor I try to update and no windows shows thors appears to do all the task of updating but theres is no windows at end to select components

**Comment by rschummer** [comment]
If you are talking about the automatic check: that means is that there are no projects with updates to download. I have mine set to run every seven days. 

If you are talking about using the menu to Check for Updates, then it should show you the form with all the projects, regardless if there are updates for the ones you previously downloaded.

**Comment by alfacero** [comment]
Yes I'm talking about using the menu to Check for Updates. Thor installs, shows the added menues but it doesn't show the windows with all the components (installed or not) when you click "check the updates"

**Comment by rschummer** [comment]
Do you have programs in the folder: Thor\Tools\Updates?

**Comment by alfacero** [comment]
Yes, it seems that I have all the programs. What I find strange are the references to "vfpxrepository".
Should not all of them have changed to github?

Example: In excelxml
http://vfpxrepository.com/dl/thorupdate/Components/ExcelXML.zip

**Comment by DougHennig** [comment]
Not all project managers have changed the Thor Check for Update process to GitHub yet, so vfpxrepository is still in place for those who have not.

**Comment by alfacero** [comment]
I found the cause of the problem:
I had downloaded the thor file from the old codeplex not from github.
I just installed it from github and it shows me the applications without problems.

Thank you very much for your support
