### ISSUE TITLE
VFP9SP2HelpFile does not install correctly

### ISSUE THREAD

**Issue by glitchvern** [VFPX/Thor#33]
VFP9SP2HelpFile is not installed correctly via Check for Updates
1. It tries and fails to install version 1.07.  The current version is 1.08
2. It does download the zipped files for 1.08 but then tries to run the 1.07 installer which doesn't exist.
3. It is trying to RUN/N _ThorInstallFolder_\Thor\Tools\Components\VFP9SP2HelpFile\dv_foxhelp_vfp9sp2_v1.07.EXE.
4. There are two zipped files in _ThorInstallFolder_\Thor\Tools\Components\VFP9SP2HelpFile\HelpFile-master\setup\ (a signed an unsigned version) containing dv_foxhelp_vfp9sp2_v1.08.exe.

### ✔️ Expected result

_What is the expected result of the above steps?_
Installation of VFP SP2 1.08 help file.

### ❌ Actual result

_What is the actual result of the above steps?_
"RUN! command failed.  The system cannot find the file specified."
The VFP SP2 1.08 help file shows as installed when Check for Updates is run again, but the help file is still clearly stock.
There may have been another error the first time this was run, but when I attempt to rerun the install I'm only getting the "RUN!" error.

**Comment by DougHennig** [comment]
This is fixed.
