### ISSUE TITLE
OOPMenu missing from THOR

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/Thor#35]
## 📝 Provide detailed reproduction steps (if any)

1. …OOPMenu is a project of VFPX
2. …Go through Thor and choose to check for updates
3. …OOPMenu is not in the project list and therefore updates are not received by people

### ✔️ Expected result

I was looking for the updated stuff that was done with OOPMenu when I discovered this was missing.

### ❌ Actual result

Ended up having to go to the project and download it myself. No big deal, but I thought someone may be interested that this is missing.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/34104227/169112848-1366c94f-97aa-4be0-8485-6f67e22e2eb6.png)

**Comment by DougHennig** [comment]
Thanks -- it was a typo. Fixed.
