### ISSUE TITLE
BeautifyX having an issue with subscript out of range

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/Thor#36]
## 📝 Provide detailed reproduction steps (if any)

1. … Have a simple program that I open and try to run BeautifyX off of the Thor toolbar
2. … Issue happens on line 123 of beautifyselectstandard
3. … see below for issue picture of code and the simple program is in the zip
4. ... nAlignASBlockMax = 0 which is the issue

### ✔️ Expected result

Successful completion

### ❌ Actual result

Error with subscript out of range

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/34104227/170588576-3bc8f745-2caa-405b-8917-f85d20e10aa1.png)
[covidrep.zip](https://github.com/VFPX/Thor/files/8782423/covidrep.zip)

**Comment by DougHennig** [comment]
No error for me with that PRG. I didn't change any of the BeautifyX settings (that I recall, anyway) so maybe it's setting-specific. Perhaps try tracing the code in BeautifyX to narrow it down.

**Comment by DougHennig** [comment]
I was able to reproduce it by changing the SELECT settings. Fixed in version 7.41.02.
