### ISSUE TITLE
oKeywordList missing

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#37]
## 📝 Provide detailed reproduction steps (if any)
After I add a property to a control, I get an "oKeywordList not found" error in the PEMEditor EditPropertyMethods method.
loISXOptions.oKeyWordList.UpdateWord(lcCleanName, .T., .T.)

It appears that the line above that, which instantiates loISXOptions via a call to  ExeScript(...'Thor_Proc_GetISXOptions') returns an object devoid of the property.

Not sure what I did to upset Thor, but indeed I have.
I recently had to move files to a new laptop and something along the way went whacko.
The last coupler of updates have not fixed the issue.

**Comment by DougHennig** [comment]
This is fixed. Choose Check for Updates from the Thor menu and update IntelliSenseX.
