### ISSUE TITLE
Error when opening Go Fish with Thor

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#39]
## 📝 Provide detailed reproduction steps (if any)

1. Got an error in thor_tool_gofish5.prg when using Thor to open GoFish
* Normal processing starts here
*  Do ... has 'End Proc' at the end of the line
 
![image](https://user-images.githubusercontent.com/34778960/197248551-67fd5e55-1462-4e26-8e36-b6b81feb5d58.png)

**Comment by DougHennig** [comment]
Fixed in the latest update.
