### ISSUE TITLE
No Apps installed or Update Status window

### ISSUE THREAD

**Issue by scriptninja** [VFPX/Thor#4]
Running Windows 10 64bit; using Thor 1.42.13 (according to its own screens)
Steps:

1. Download Thor from Github (tried both downloading the archive and cloning with git)
1. Place Thor in the folder where I intend to use it
1. Open Visual Foxpro 9
1. CLEAR ALL
1. `cd <path_to_thor>` (also tried using entire path on next line)
1. `DO Thor.APP`

Expected result:

*   create a folder named Thor in the installation folder
*   create some sub-folders and files in that folder
*   update the VFP system menu (by adding a menu pad for Thor)
*   run ["Check for Updates"](Thor_one-click_update.md) so that you it can download and install [PEM Editor](https://github.com/VFPX/PEMEditor) and [The Thor Repository](Thor_repository.md), which are necessary components for Thor
*   and open the Thor form.

Actual result:

*   create a folder named Thor in the installation folder
*   create some sub-folders and files in that folder
*   update the VFP system menu (by adding a menu pad for Thor and one for Thor Tools)
*   run ["Check for Updates"](Thor_one-click_update.md) (I think this is happening; see below)
*   open Thor Configuration
*   There are 63 .prg files in the Tools\Updates folder, including `Thor_Update_PEMEditor.PRG`
*   Thor\Tools\Apps is empty (the discussion in #3 gives me the impression this shouldn't be the case)
*   Neither as a result of `DO Thor.APP` nor in response to the "Check for Updates" menu option does the  "Thor: Update Status" window shown in the documentation ever appear. The status messages shown in response to "Check for Updates" do seem to be the same as what happens at what seems to be the point where `DO Thor.APP` should be performing the check for updates.
*   Menu items do not seem useful:
    *  "Manage Plugins" presents busy cursor a few times and then does nothing
    * "Launcher" opens; only "Settings & Misc." and "Thor" categories are available, and "Run Tool" seems to cause errors and start debugging for all entries I've tried ("Class definition EDITORWIN is not found" for example when trying to launch "All Thor Repository Tools")
    * "Thor Configuration" seems to work, I think, to the extent it is useful with no tools installed
    * "Check for Updates" runs through quite a few status messages, and in the process empties and refills the Updates folder

After installing Thor and then also installing PEMEditor manually, I had tools available and some of the errors go away, but "Check for Updates" behaved the same and still didn't give me any opportunity to install anything else form the Thor repository. This led me to try downloading the Thor repository manually from Github and unzipping it to the Tools folder, which seems to have provided me with proper access to all the tools in that repository, but still no update status form at the end of the Check for Updates process, and what drew me to Thor in the first place was the idea of an easy way to keep foxbin2prg and Project Explorer up to date...

**Comment by DougHennig** [comment]
All of these issues should be fixed now. Delete the Thor folder, download the latest version and run it, and install IntelliSenseX, Thor Repository, and PEM Editor when the Check for Updates dialog appears, since those are required by Thor.
