### ISSUE TITLE
Ole error code 0x80029c4a

### ISSUE THREAD

**Issue by parios59** [VFPX/Thor#5]
Loading Thor launcher?

OLE ERROR CODE 0X80029c4a: error loading type library/dll. ole object is being ignored. 

anyone clues?

**Comment by DougHennig** [comment]
Hi Pete.

The Thor Launcher uses the TreeView control so it sounds like that ActiveX control must not be properly installed or is corrupted on your machine.

Doug

**Comment by parios59** [comment]
Thanks Doug,
     Figured out since my system is connected to a domain and also Citrix/DAAS enviornment - security gpo / update from the DAAS enviornment disabled certain activeX controls.   Got it to work by logging on to the local admin account and running it on that account and then having the GPO policies changed to allow.... 

FYI - thanks - it had been working well for so long - i didn't think out of box.... duh... thanks again and hope all is well..

Pete
