### ISSUE TITLE
Parameterproblem in Case of SET POINT TO , (comma) and calling thor_proc_getfieldnames.prg | Must specify additional parameters

### ISSUE THREAD

**Issue by ToniKoehler** [VFPX/Thor#6]
The following classes, crashes into error-message "Must specify additional parameters" if the VFP-Environment is set to:

SET POINT TO "," (comma)
SET DECIMALS TO 1 (or higher)  [In my example is set to 4]
SET FIXED ON

- Class othor of Classlib thor.vcx
Method "ExecuteThorProc"
Error comes in line 21 because lcParams have more then 4 parameters
In line 16 the transform works wrong with comma as SET("POINT").

- Class thor_run of Classlib thor_run.vcx,
Method "AssignThorDispatcher -> Procedure ExecuteThorProc
Error comes in line 219 because lcParams have more then 4 parameters
In line 214 the transform works wrong with comma as SET("POINT").

Here is the problem:
TRANSFORM(1)   *displays    1,000

So lcParams becomes additional parameters like "with lxP1, lxP2,000, lxP3,000, lxP4,000"
The thor_proc_getfieldnames.prg but have only 4 parameters. In this case the PCOUNT() = 7 !!!

It's very easy to fix.
---> Switch the TRANSFORM() to ALLTRIM(STRING())

**Comment by DougHennig** [comment]
Fixed in the latest commit.
