### ISSUE TITLE
Property 'cthordispatcher' value is too long. 

### ISSUE THREAD

**Issue by Tracy-P** [VFPX/Thor#7]
Start a VFP just from the original icon. No config.fpw, no code run.
DO C:\Work\Tools\Thor\Thor\Thor\RunThor.prg
Menu -> Thor -> Check for Udpates
Cancel, or Install Updates it doesn't matter

Click on the _Screen background
I get the error

Microsoft Visual FoxPro
OK
Help
Property 'cthordispatcher' value is too long.

?LEN(ALLTRIM(_Screen.cThordispatcher)) && 8319

Display Memory shows 
0 variables defined, 0 bytes used
16 Popups Defined

I have the Document View, Properties, and Data Session windows docked on the right side of the screen in tabs.
I have the Command window docked on the bottom beneath those.

This happens on 2 different workstations.

[Cross posted on the old Google Forum]

**Comment by DougHennig** [comment]
I can't reproduce that so you'll likely have to trace the code to see what's happening.

**Comment by Tracy-P** [comment]
SET COVERAGE TO "c:\temp\testcoverage.csv"
DEBUG
set Trace between calls

click to get the error. 
Nothing in the Debug window.
Nothing in the coverage file

Version() returns Visual FoxPro 9.00.0000.7423 for Windows

This is happening on both a Windows 7 OS (in a VM)
and my personal Windows 10 Home laptop.

What else could I do to track down how this is being triggered?

**Comment by Tracy-P** [comment]
I wrote a quick errorcatcher prg and set On Error do errorcatcher
If I type something in the Command window, it catches the error.
When I click on the _Screen background, it does not catch the error.

**Comment by Tracy-P** [comment]
Okay. I am using the default Properties window. It is open when I do this.
Once I close the Properties window the error stops happening.

**Comment by DougHennig** [comment]
Sorry, still no repo for me. What's the content of _Screen.cThordispatcher (you should be able to see it in the Properties window)?

**Comment by Tracy-P** [comment]
[cthordispatcher.tracy.txt](https://github.com/VFPX/Thor/files/2903039/cthordispatcher.tracy.txt)

**Comment by DougHennig** [comment]
_Screen.cThorDispatcher is set near the end of the AssignThorDispatcher method in Thor_Run in Thor_Run.vcx so perhaps start tracing the code in that area.

**Comment by Tracy-P** [comment]
Well, you've pointed me the place that needs to be changed. 
There's a few things that need to be corrected in that method. 
I was able to reduce the size of that property to 7861 characters.
I'll work on sending you a pull request in the next couple of days. 
My plans are 
`Text To lcThorExecute Noshow TEXTMERGE`
becomes
`Text To lcThorExecute Noshow TEXTMERGE PRETEXT 1+2+4`

remove the comment in the middle, That's about 300 characters.

remove the following line that are right after the EndText
`lcThorExecute = Chrtran(lcThorExecute, ccCR + ccCR, ccCR)`
It wasn't working and would no longer be needed. The PRETEXT at the top would be doing what this was meant to do, then some more.

There would be about 8 or more characters saved by tweaking some inline spaces used for making the code easier to read, but that won't be needed.

Since I'm just starting to tinker with Thor, I'm not sure anything is going to break with this suggested change. Looking at the code, all I'm really doing is a minification of sorts.

**Comment by Tracy-P** [comment]
Now that I'm looking at this project. It isn't using FoxBin2Prg. All the binary files are just there. So sending a PullRequest isn't a safe option. 
Do you want to push a change with all the FoxBin2Prg files in place? Then I can fork it and just send you a pull request of the thor_run.vc2 changes I suggest in the method mentioned above.

**Comment by DougHennig** [comment]
Done.

**Comment by Tracy-P** [comment]
I've issued the pull request. Thank you.
#8
