### ISSUE TITLE
How to test Thor update private

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#76]
I try to alter one of the Thor Tools window upgrading GoFish. It fails.   
See https://github.com/VFPX/GoFish/issues/59 for the problem.   

Is there a way to debug Thor so that I do not need to push into production?

Thanks

Lutz

**Comment by Jimrnelson** [comment]
This topic is poorly named -- something along the lines of "How to run a private (test) CFU of a project before releasing it into the wild." would be an improvement.

**Comment by lscheffler** [comment]
But such a topic would end up tl;dr; :D

**Comment by Jimrnelson** [comment]
> But such a topic would end up tl;dr; :D

Not at all -- Thor already supports it, and we (Matt and I) used it extensively when GF was undergoing constant upgrades. 

It's merely a task (for me) to identify the steps and to document them.

**Comment by lscheffler** [comment]
I mean the epic topic name is tl;dr;

**Comment by lscheffler** [comment]
@Jimrnelson Anyway, any idea how to do the test in private?

**Comment by Jimrnelson** [comment]
@lscheffler  

Lutz --

It will take some time for me to be able to explain how to download private projects in CFU.  (This would allow you to have a separate test version of GF that would be available to you only -- and, if you chose, others users for testing)

- There is considerable complexity in getting all the parts right.
- I really have not worked on this part of Thor in close to a decade.
- There have been very few uses of this over the entire lifespan of Thor CFU.

**Comment by lscheffler** [comment]
Anything that solves the problem that I can not alter the menu of GoFish is welcome. I can only search if I find a way to see what is going on during update - inside GoFish. I hardly will put out Thor-debug versions of GoFish to public.   
Or do you see any documentation that tells my how this specific Thor update will work? I have some Thor projects here and any does something different with Thor. It's a riddle.

**Comment by Jimrnelson** [comment]
> Anything that solves the problem that I can not alter the menu of GoFish is welcome. I can only search if I find a way to see what is going on during update - inside GoFish. 

See my earlier message.  This process is neither simple or documented.  No shortcuts either.

**Comment by lscheffler** [comment]
So it's the unmaintainable main tool all this works depends on? Ouch. I guess I check how much gin is available and calm down.
