### ISSUE TITLE
Thor update form opens on wrong monitor

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#83]
## 📝 Provide detailed reproduction steps (if any)

1. Multi monitor setup
2. Main monitor is not center
3. VFP is not on main monitor
4. VFP monitor is DPI scaled, main not
5. Run Thor update
6. Move Update form in the VFP Screen area
7. Close Thor Update form
8. Run Thor Update

### ✔️ Expected result
Update form opens on last position

### ❌ Actual result
Update form opens in main monitor, at bottom of the monitor, at the monitor border next to the VFP screen.   
If centred on the main monitor, closed and rerun, it opens on main monitor with left kept, but at bottom

Moved from #75

**Comment by Jimrnelson** [comment]
@lscheffler 

Can I get you interested in handling this?  This is right up your alley and you are better able to test it than I am.

The form is:       _Screen.cThorFolder + "\Tools\checkforupdates.scx"

I believe you should be able to simply replace the recently added lines in the Init.

If you handle this, you can just attach the SC2 file here.

Thanks (I hope).

**Comment by lscheffler** [comment]
@Jimrnelson I'm a bit lost. This week's a different planet.   
 What do you like me to test? In simple terms, pls.

**Comment by Jimrnelson** [comment]
@lscheffler 

Lutz --

This issue, which you opened, is to fix the issue where Thor's "Check For Updates" form opens on the wrong monitor.

I am asking if you are interested in fixing the problem, which is found in this form (in your local Thor):

_Screen.cThorFolder + "\Tools\checkforupdates.scx"

The form is call in this prg:

 _screen.cThorFolder + '\Tools\Procs\Thor_Proc_DownloadAndInstallUpdates.PRG'

You can work on this by putting a stop in the PRG right before the form is opened, then running Check For Updates.

If you do work on this, you can just send me the SC2 file.

I hope this makes more sense.

**Comment by lscheffler** [comment]
Ah, the entry point to the form. I will see what I can do.

**Comment by lscheffler** [comment]
The solution will move the form into _SCREEN if out of the visible area, else the form will not be touched.
Add to **_screen.cThorFolder + '\Tools\Procs\Thor_Proc_DownloadAndInstallUpdates.PRG'**:
```
Procedure ThorUp_GetMonitorStatistics
************************************************************************
* Thor_GetMonitorStatistics
****************************************
***  Function: Returns information about the desktop screen
***            Can be used to check for desktop width and size
***            and determine when a second monitor is disabled
***            and layout needs to be adjusted to keep the
***            window visible.
***      Pass:
***    Return:  Monitor Object
***
*** From https://west-wind.com/wconnect/weblog/ShowEntry.blog?id=836
*** Handling Multiple Screens in Visual FoxPro Desktop Applications
***
************************************************************************

	#Define SM_CXFULLSCREEN		16
	#Define SM_CYFULLSCREEN		17

	#Define SM_XVIRTUALSCREEN	76
	#Define SM_YVIRTUALSCREEN	77
	#Define SM_CXVIRTUALSCREEN	78
	#Define SM_CYVIRTUALSCREEN	79
	#Define SM_CMONITORS		80

	#Define SM_XVIRTUALSCREEN	76
	#Define SM_YVIRTUALSCREEN	77
	#Define SM_CXVIRTUALSCREEN	78
	#Define SM_CYVIRTUALSCREEN	79


	Local;
		loMonitor As "EMPTY"

	Declare Integer GetSystemMetrics In user32 Integer nIndex

	loMonitor = Createobject("EMPTY")
*	AddProperty(loMonitor, "gnMonitors",      GetSystemMetrics(SM_CMONITORS))

	AddProperty(m.loMonitor, "gnVirtualLeft",   GetSystemMetrics(SM_XVIRTUALSCREEN))
	AddProperty(m.loMonitor, "gnVirtualTop",    GetSystemMetrics(SM_YVIRTUALSCREEN))

	AddProperty(m.loMonitor, "gnVirtualWidth",  GetSystemMetrics(SM_CXVIRTUALSCREEN))
	AddProperty(m.loMonitor, "gnVirtualHeight", GetSystemMetrics(SM_CYVIRTUALSCREEN))

	AddProperty(m.loMonitor, "gnVirtualRight",  m.loMonitor.gnVirtualWidth -  Abs(m.loMonitor.gnVirtualLeft) - 10)
	AddProperty(m.loMonitor, "gnVirtualBottom", m.loMonitor.gnVirtualHeight - Abs(m.loMonitor.gnVirtualTop)  -  5)

*ADDPROPERTY(loMonitor, "gnScreenHeight",  GetSystemMetrics(SM_CYFULLSCREEN))
*ADDPROPERTY(loMonitor, "gnScreenWidth",   GetSystemMetrics(SM_CXFULLSCREEN))

	Return m.loMonitor

Endproc &&ThorUp_GetMonitorStatistics

```
and replace method init of **_Screen.cThorFolder + "\Tools\checkforupdates.scx"**
```
* ThorFormSettings home page = http://vfpx.codeplex.com/wikipage?title=Thor%20Framework%20FormSettings
Local laColumnOrder[1], laColumnWidths[1], lnI, loSettings

loSettings = Execscript (_Screen.cThorDispatcher, 'Class= ThorFormSettings', 'Thor Install Updates Settings')
Thisform.AddProperty ('oSettings', loSettings)

*!*	changed by: SF 1.4.2023
*!*	<pdm>
*!*	<change date="{^2023-04-01,17:21:00}">changed by: SF<br />
*!*	Try to move form into visible area if on multi-monitor setup with _VFP not on main monitor
*!*	This part helps to get a good start before reading settings stored. Else it will be odd.
*!*	</change>
*!*	</pdm>

If This.Desktop Or This.Dockable=1 Then
*Move forms with this setting into screen, might be odd on multiple monitors

*get coords of vfp
	This.Top  = _Screen.Top
	This.Left = _Screen.Left
*twice, first reads odd values
	This.Top  = _Screen.Top
	This.Left = _Screen.Left
Endif &&This.Desktop Or This.Dockable=1

*!*	/changed by: SF 1.4.2023

This.MinWidth  = This.Width
This.MinHeight = This.Height

If Not Isnull(loSettings)
	loSettings.Restore (Thisform) && Gets top, left, height, width

	loSettings.Restore (Thisform, 'cColumnWidths, cColumnOrder, nSplitterTop') && and two other propertie

*!*	changed by: SF 1.4.2023
*!*	<pdm>
*!*	<change date="{^2023-04-01,17:21:00}">changed by: SF<br />
*!*	Try to move form into visible area if on multi-monitor setup with _VFP not on main monitor
*!*	This part moves the form into _SCREEN, if partial out of visble area.
*!*	</change>
*!*	</pdm>

*!*		With This
*!*			.Height	= Min(.Height, _Screen.Height)
*!*			.Top	= Max(0, Min(.Top, _Screen.Height - .Height))

*!*			.Width = Min(.Width, _Screen.Width)
*!*			.Left  = Max(0, Min(.Left, _Screen.Width - .Width))

*!*		Endwith

*********
	lnTop          = 0
	lnHeight       = This.Height
	lnLeft         = 0
	lnWidth        = This.Width

	lnScreenTop    = 0
	lnScreenBottom = _Screen.Height
	lnScreenLeft   = 0
	lnScreenRight  = _Screen.Width

	If This.Desktop Or This.Dockable=1 Then
		loMonitor = ThorUp_GetMonitorStatistics()

		lnTop          = _Screen.Top
		lnLeft         = _Screen.Left

		lnScreenTop    = m.loMonitor.gnVirtualTop
		lnScreenBottom = m.loMonitor.gnVirtualBottom
		lnScreenLeft   = m.loMonitor.gnVirtualLeft
		lnScreenRight  = m.loMonitor.gnVirtualRight

	Endif &&This.Desktop Or This.Dockable=1

	If Between(This.Top , m.lnScreenTop, m.lnScreenBottom) Then
		lnTop    = This.Top
		lnHeight = This.Height
	Endif &&Between(This.Top , m.lnScreenTop, m.lnScreenBottom)

	If Between(This.Left, m.lnScreenLeft, m.lnScreenRight) Then
		lnLeft   = This.Left
		lnWidth  = This.Width
	Endif &&Between(This.Left, m.lnScreenLeft, m.lnScreenRight)

	Thisform.Move(m.lnLeft, m.lnTop, m.lnWidth, m.lnHeight)

	This.Resize()
*!*	/changed by: SF 1.4.2023

Endif
```
If this form is dockable / desktop all the time you might remove the IFs and superfluous code, I just pasted the full version out of GoFish

**Comment by Jimrnelson** [comment]
@lscheffler 

I have released this code (although I cannot test the multiple monitor situation).

Please verify that this issue can now be closed.

BTW, your signature in code says "SF" ... I had seen that before and wondered who it was.  I don't understand it; can you explain?  (and perhaps my signature JRN is confusing to you?)

**Comment by lscheffler** [comment]
Form works, I close   
If you like to check yourself:
- Run _VFP not maximized
- run the update form and close somewhere inside the monitor
- rerun, it opens at position stored
- move the upper left corner out of the monitor
- close and rerun.
- It should open inside _SCREEN

----
SF? I do not know how this works overseas, but we had this system of *short signs* in letter-based communication or paper forms inside the company. So everybody sending letters had a distinct short sign. Commonly **F**irst_name**L**ast_name **FL**.  Because LS was the ass hole son of the owner at my first employment, the code was not reused after he was fired and I stuck with SF since then. It made into computer files. At this time I was doing hardware and I moved my desk a long chain along different owners and companies doing the same job, where we need the keep the system, and I finally was used to it. It's still in my ticketing system, even as I'm now the sole worker and owner.

BTW the PDM codes fit to [Project Documenting Machine](http://gorila.netlab.cz/pdm.html) of Martina Jindrová - I'm used to this as well, you can remove the superfluous if you like. I just tend to mindlessly insert the codes. Intellisense at work.

**Comment by Jimrnelson** [comment]
Thanks, I will mark this as complete.

We do initials here (USA) as well, usually first/last, occasionally first/middle/last (I've always used JRN)
