### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GTGeek88** [VFPX/Thor#9]
I had a problem during install. Multiple errors. I was bad and did not write them down. I unzipped Thor into C:\THOR.  This created, if I remember correctly, C:\THOR\THOR-MASTER and some folders under that. I changed the default folder in VFP to C:\THOR\THOR-MASTER\THOR, where THOR.APP resides, and then from the Command window I ran the Thor app (DO THOR.APP).  I'm unsure what the error messages were, but I did try running VFP with admin rights tried it again. Same errors. Now that I'm typing this, I'm thinking maybe the APP needed to be recompiled under VFP 8, which is what this client is running. I did not think of that at the time and I am no longer onsite to try it.

**Comment by DougHennig** [comment]
First, without error messages, I can't help. Second, although I didn't write Thor, I have a strong suspicion it requires VFP 9.

**Comment by GTGeek88** [comment]
Suspicion? Sarcasm? I blew right past the line that says "requires VFP 9." I've been using 9 for so long and Thor for so long, I did not realize it required VFP 9. Thought it might have been like SDT, where you could recompile it in VFP 8 (or even 7, I think). Well, I think the client has VFP 9, so I guess I'll be installing that!

Your name is on the project as a designer and as the implementer of the interface, but I guess Jim did most of the behind the scenes stuff and PEME, etc.

**Comment by DougHennig** [comment]
No, I wasn't being sarcastic; I missed the "Requires VFP9" statement as well.
