### ISSUE TITLE
wwDotNetBridge

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#95]
Is there an default access to wwDotNetBridge with Thor, and if, how?

**Comment by Jimrnelson** [comment]
@lscheffler 

Actually, there's a lot **less** to Thor than you and almost everybody else imagines.  It really only does two things:

[1]  It delivers zip files ("projects") and unzips them using "Check For Updates" (CFU).  There are hooks for these projects to create their own "Thor Tools",  if appropriate.  GF does so; most other project do not.  (In this sense, Thor is simply like a FedEX delivery truck.)

[2]  It provides a UI to make these tools easily accessible (Hot keys, pop-up menus, system menu pad, tool bar).  And in this sense Thor is like the UI on your smart phone or tablet that allows you to configure your screen the way you like it.

"Thor Tools" are simply PRGs satisfying a simple structure which makes them discoverable by Thor.   These tools can be delivered by downloading the "Thor Repository" (a project), any other project that creates a tool, or created by a user for their own needs.

To answer your question then -- no, there is no default access to wwDotNetBridge, or any other application, for that matter.

**Comment by lscheffler** [comment]
:) I was just asking. On other steps you seem to rely on something provided by Thor, like on https://github.com/VFPX/GoFish/issues/58#issuecomment-1464899249. Thor is a riddle to me. :)

**Comment by Jimrnelson** [comment]
"Used by Thor", in this case, is a common way of stating that it uses some tools and procedures from projects assumed to be downloaded from CFU, which include the "Thor repository" and "PEMEditor".  These are automatically checked off when you run CFU, but not required.  Am pretty sure that GF uses them if available but does not otherwise fail.

**Comment by Jimrnelson** [comment]
RE: riddle --

See my earlier note.  Thor proper does not really do much.

However, when a number of projects are downloaded, some of which are closely integrated, there's a lot of magic.

**Comment by lscheffler** [comment]
> "Used by Thor", in this case, is a common way of stating that it uses some tools and procedures from projects assumed to be downloaded from CFU, which include the "Thor repository" and "PEMEditor". These are automatically checked off when you run CFU, but not required. Am pretty sure that GF uses them if available but does not otherwise fail.

I see what you mean. Thanks for clarification. :)
